// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend/internal/pkg/db/model"
)

func newAbandonCode(db *gorm.DB, opts ...gen.DOOption) abandonCode {
	_abandonCode := abandonCode{}

	_abandonCode.abandonCodeDo.UseDB(db, opts...)
	_abandonCode.abandonCodeDo.UseModel(&model.AbandonCode{})

	tableName := _abandonCode.abandonCodeDo.TableName()
	_abandonCode.ALL = field.NewAsterisk(tableName)
	_abandonCode.Idx1 = field.NewInt32(tableName, "idx1")
	_abandonCode.Col1 = field.NewString(tableName, "col1")
	_abandonCode.Idx2 = field.NewInt32(tableName, "idx2")
	_abandonCode.Idx3 = field.NewInt32(tableName, "idx3")

	_abandonCode.fillFieldMap()

	return _abandonCode
}

type abandonCode struct {
	abandonCodeDo abandonCodeDo

	ALL  field.Asterisk
	Idx1 field.Int32
	Col1 field.String
	Idx2 field.Int32
	Idx3 field.Int32

	fieldMap map[string]field.Expr
}

func (a abandonCode) Table(newTableName string) *abandonCode {
	a.abandonCodeDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a abandonCode) As(alias string) *abandonCode {
	a.abandonCodeDo.DO = *(a.abandonCodeDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *abandonCode) updateTableName(table string) *abandonCode {
	a.ALL = field.NewAsterisk(table)
	a.Idx1 = field.NewInt32(table, "idx1")
	a.Col1 = field.NewString(table, "col1")
	a.Idx2 = field.NewInt32(table, "idx2")
	a.Idx3 = field.NewInt32(table, "idx3")

	a.fillFieldMap()

	return a
}

func (a *abandonCode) WithContext(ctx context.Context) *abandonCodeDo {
	return a.abandonCodeDo.WithContext(ctx)
}

func (a abandonCode) TableName() string { return a.abandonCodeDo.TableName() }

func (a abandonCode) Alias() string { return a.abandonCodeDo.Alias() }

func (a abandonCode) Columns(cols ...field.Expr) gen.Columns { return a.abandonCodeDo.Columns(cols...) }

func (a *abandonCode) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *abandonCode) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 4)
	a.fieldMap["idx1"] = a.Idx1
	a.fieldMap["col1"] = a.Col1
	a.fieldMap["idx2"] = a.Idx2
	a.fieldMap["idx3"] = a.Idx3
}

func (a abandonCode) clone(db *gorm.DB) abandonCode {
	a.abandonCodeDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a abandonCode) replaceDB(db *gorm.DB) abandonCode {
	a.abandonCodeDo.ReplaceDB(db)
	return a
}

type abandonCodeDo struct{ gen.DO }

func (a abandonCodeDo) Debug() *abandonCodeDo {
	return a.withDO(a.DO.Debug())
}

func (a abandonCodeDo) WithContext(ctx context.Context) *abandonCodeDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a abandonCodeDo) ReadDB() *abandonCodeDo {
	return a.Clauses(dbresolver.Read)
}

func (a abandonCodeDo) WriteDB() *abandonCodeDo {
	return a.Clauses(dbresolver.Write)
}

func (a abandonCodeDo) Session(config *gorm.Session) *abandonCodeDo {
	return a.withDO(a.DO.Session(config))
}

func (a abandonCodeDo) Clauses(conds ...clause.Expression) *abandonCodeDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a abandonCodeDo) Returning(value interface{}, columns ...string) *abandonCodeDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a abandonCodeDo) Not(conds ...gen.Condition) *abandonCodeDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a abandonCodeDo) Or(conds ...gen.Condition) *abandonCodeDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a abandonCodeDo) Select(conds ...field.Expr) *abandonCodeDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a abandonCodeDo) Where(conds ...gen.Condition) *abandonCodeDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a abandonCodeDo) Order(conds ...field.Expr) *abandonCodeDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a abandonCodeDo) Distinct(cols ...field.Expr) *abandonCodeDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a abandonCodeDo) Omit(cols ...field.Expr) *abandonCodeDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a abandonCodeDo) Join(table schema.Tabler, on ...field.Expr) *abandonCodeDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a abandonCodeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *abandonCodeDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a abandonCodeDo) RightJoin(table schema.Tabler, on ...field.Expr) *abandonCodeDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a abandonCodeDo) Group(cols ...field.Expr) *abandonCodeDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a abandonCodeDo) Having(conds ...gen.Condition) *abandonCodeDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a abandonCodeDo) Limit(limit int) *abandonCodeDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a abandonCodeDo) Offset(offset int) *abandonCodeDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a abandonCodeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *abandonCodeDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a abandonCodeDo) Unscoped() *abandonCodeDo {
	return a.withDO(a.DO.Unscoped())
}

func (a abandonCodeDo) Create(values ...*model.AbandonCode) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a abandonCodeDo) CreateInBatches(values []*model.AbandonCode, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a abandonCodeDo) Save(values ...*model.AbandonCode) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a abandonCodeDo) First() (*model.AbandonCode, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AbandonCode), nil
	}
}

func (a abandonCodeDo) Take() (*model.AbandonCode, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AbandonCode), nil
	}
}

func (a abandonCodeDo) Last() (*model.AbandonCode, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AbandonCode), nil
	}
}

func (a abandonCodeDo) Find() ([]*model.AbandonCode, error) {
	result, err := a.DO.Find()
	return result.([]*model.AbandonCode), err
}

func (a abandonCodeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AbandonCode, err error) {
	buf := make([]*model.AbandonCode, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a abandonCodeDo) FindInBatches(result *[]*model.AbandonCode, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a abandonCodeDo) Attrs(attrs ...field.AssignExpr) *abandonCodeDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a abandonCodeDo) Assign(attrs ...field.AssignExpr) *abandonCodeDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a abandonCodeDo) Joins(fields ...field.RelationField) *abandonCodeDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a abandonCodeDo) Preload(fields ...field.RelationField) *abandonCodeDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a abandonCodeDo) FirstOrInit() (*model.AbandonCode, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AbandonCode), nil
	}
}

func (a abandonCodeDo) FirstOrCreate() (*model.AbandonCode, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AbandonCode), nil
	}
}

func (a abandonCodeDo) FindByPage(offset int, limit int) (result []*model.AbandonCode, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a abandonCodeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a abandonCodeDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a abandonCodeDo) Delete(models ...*model.AbandonCode) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *abandonCodeDo) withDO(do gen.Dao) *abandonCodeDo {
	a.DO = *do.(*gen.DO)
	return a
}
