// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend/internal/pkg/db/model"
)

func newAppSetting(db *gorm.DB, opts ...gen.DOOption) appSetting {
	_appSetting := appSetting{}

	_appSetting.appSettingDo.UseDB(db, opts...)
	_appSetting.appSettingDo.UseModel(&model.AppSetting{})

	tableName := _appSetting.appSettingDo.TableName()
	_appSetting.ALL = field.NewAsterisk(tableName)
	_appSetting.Key = field.NewString(tableName, "key")
	_appSetting.Value = field.NewString(tableName, "value")
	_appSetting.UpdatedAt = field.NewTime(tableName, "updated_at")

	_appSetting.fillFieldMap()

	return _appSetting
}

type appSetting struct {
	appSettingDo appSettingDo

	ALL       field.Asterisk
	Key       field.String
	Value     field.String
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (a appSetting) Table(newTableName string) *appSetting {
	a.appSettingDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a appSetting) As(alias string) *appSetting {
	a.appSettingDo.DO = *(a.appSettingDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *appSetting) updateTableName(table string) *appSetting {
	a.ALL = field.NewAsterisk(table)
	a.Key = field.NewString(table, "key")
	a.Value = field.NewString(table, "value")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *appSetting) WithContext(ctx context.Context) *appSettingDo {
	return a.appSettingDo.WithContext(ctx)
}

func (a appSetting) TableName() string { return a.appSettingDo.TableName() }

func (a appSetting) Alias() string { return a.appSettingDo.Alias() }

func (a appSetting) Columns(cols ...field.Expr) gen.Columns { return a.appSettingDo.Columns(cols...) }

func (a *appSetting) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *appSetting) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 3)
	a.fieldMap["key"] = a.Key
	a.fieldMap["value"] = a.Value
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a appSetting) clone(db *gorm.DB) appSetting {
	a.appSettingDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a appSetting) replaceDB(db *gorm.DB) appSetting {
	a.appSettingDo.ReplaceDB(db)
	return a
}

type appSettingDo struct{ gen.DO }

func (a appSettingDo) Debug() *appSettingDo {
	return a.withDO(a.DO.Debug())
}

func (a appSettingDo) WithContext(ctx context.Context) *appSettingDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a appSettingDo) ReadDB() *appSettingDo {
	return a.Clauses(dbresolver.Read)
}

func (a appSettingDo) WriteDB() *appSettingDo {
	return a.Clauses(dbresolver.Write)
}

func (a appSettingDo) Session(config *gorm.Session) *appSettingDo {
	return a.withDO(a.DO.Session(config))
}

func (a appSettingDo) Clauses(conds ...clause.Expression) *appSettingDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a appSettingDo) Returning(value interface{}, columns ...string) *appSettingDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a appSettingDo) Not(conds ...gen.Condition) *appSettingDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a appSettingDo) Or(conds ...gen.Condition) *appSettingDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a appSettingDo) Select(conds ...field.Expr) *appSettingDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a appSettingDo) Where(conds ...gen.Condition) *appSettingDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a appSettingDo) Order(conds ...field.Expr) *appSettingDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a appSettingDo) Distinct(cols ...field.Expr) *appSettingDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a appSettingDo) Omit(cols ...field.Expr) *appSettingDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a appSettingDo) Join(table schema.Tabler, on ...field.Expr) *appSettingDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a appSettingDo) LeftJoin(table schema.Tabler, on ...field.Expr) *appSettingDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a appSettingDo) RightJoin(table schema.Tabler, on ...field.Expr) *appSettingDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a appSettingDo) Group(cols ...field.Expr) *appSettingDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a appSettingDo) Having(conds ...gen.Condition) *appSettingDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a appSettingDo) Limit(limit int) *appSettingDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a appSettingDo) Offset(offset int) *appSettingDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a appSettingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *appSettingDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a appSettingDo) Unscoped() *appSettingDo {
	return a.withDO(a.DO.Unscoped())
}

func (a appSettingDo) Create(values ...*model.AppSetting) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a appSettingDo) CreateInBatches(values []*model.AppSetting, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a appSettingDo) Save(values ...*model.AppSetting) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a appSettingDo) First() (*model.AppSetting, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppSetting), nil
	}
}

func (a appSettingDo) Take() (*model.AppSetting, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppSetting), nil
	}
}

func (a appSettingDo) Last() (*model.AppSetting, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppSetting), nil
	}
}

func (a appSettingDo) Find() ([]*model.AppSetting, error) {
	result, err := a.DO.Find()
	return result.([]*model.AppSetting), err
}

func (a appSettingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AppSetting, err error) {
	buf := make([]*model.AppSetting, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a appSettingDo) FindInBatches(result *[]*model.AppSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a appSettingDo) Attrs(attrs ...field.AssignExpr) *appSettingDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a appSettingDo) Assign(attrs ...field.AssignExpr) *appSettingDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a appSettingDo) Joins(fields ...field.RelationField) *appSettingDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a appSettingDo) Preload(fields ...field.RelationField) *appSettingDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a appSettingDo) FirstOrInit() (*model.AppSetting, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppSetting), nil
	}
}

func (a appSettingDo) FirstOrCreate() (*model.AppSetting, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AppSetting), nil
	}
}

func (a appSettingDo) FindByPage(offset int, limit int) (result []*model.AppSetting, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a appSettingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a appSettingDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a appSettingDo) Delete(models ...*model.AppSetting) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *appSettingDo) withDO(do gen.Dao) *appSettingDo {
	a.DO = *do.(*gen.DO)
	return a
}
