DROP TABLE IF EXISTS abandon_code;
CREATE TABLE abandon_code (
  idx1 INTEGER NOT NULL PRIMARY KEY,
  col1 TEXT NOT NULL,

  idx2 INTEGER NOT NULL,
  idx3 INTEGER NOT NULL
);

CREATE UNIQUE INDEX idx_2_3 ON abandon_code (idx2, idx3);
