/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("AbandonCodeCURDApi", () => {
  let instance: api.AbandonCodeCURDApi
  beforeEach(function() {
    instance = new api.AbandonCodeCURDApi(config)
  });

  test("abandonCodeCURDAddAbandonCode", () => {
    const body: api.ApiAddAbandonCodeRequest = undefined
    return expect(instance.abandonCodeCURDAddAbandonCode(body, {})).resolves.toBe(null)
  })
  test("abandonCodeCURDDelAbandonCodeByIdx1List", () => {
    const idx1List: Array<number> = undefined
    return expect(instance.abandonCodeCURDDelAbandonCodeByIdx1List(idx1List, {})).resolves.toBe(null)
  })
  test("abandonCodeCURDGetAbandonCodeList", () => {
    const idx1List: Array<number> = undefined
    const idx2List: Array<number> = undefined
    const idx3List: Array<number> = undefined
    return expect(instance.abandonCodeCURDGetAbandonCodeList(idx1List, idx2List, idx3List, {})).resolves.toBe(null)
  })
  test("abandonCodeCURDUpdateAbandonCode", () => {
    const body: api.ApiUpdateAbandonCodeRequest = undefined
    return expect(instance.abandonCodeCURDUpdateAbandonCode(body, {})).resolves.toBe(null)
  })
})

describe("DefaultCURDApi", () => {
  let instance: api.DefaultCURDApi
  beforeEach(function() {
    instance = new api.DefaultCURDApi(config)
  });

  test("defaultCURDAddAppSetting", () => {
    const body: api.ApiAddAppSettingRequest = undefined
    return expect(instance.defaultCURDAddAppSetting(body, {})).resolves.toBe(null)
  })
  test("defaultCURDAddPhoto", () => {
    const body: api.ApiAddPhotoRequest = undefined
    return expect(instance.defaultCURDAddPhoto(body, {})).resolves.toBe(null)
  })
  test("defaultCURDAddPhotoGroup", () => {
    const body: api.ApiAddPhotoGroupRequest = undefined
    return expect(instance.defaultCURDAddPhotoGroup(body, {})).resolves.toBe(null)
  })
  test("defaultCURDAddTimelineEvent", () => {
    const body: api.ApiAddTimelineEventRequest = undefined
    return expect(instance.defaultCURDAddTimelineEvent(body, {})).resolves.toBe(null)
  })
  test("defaultCURDDelAppSettingByKeyList", () => {
    const keyList: Array<string> = undefined
    return expect(instance.defaultCURDDelAppSettingByKeyList(keyList, {})).resolves.toBe(null)
  })
  test("defaultCURDDelPhotoByIDList", () => {
    const iDList: Array<string> = undefined
    return expect(instance.defaultCURDDelPhotoByIDList(iDList, {})).resolves.toBe(null)
  })
  test("defaultCURDDelPhotoGroupByIDList", () => {
    const iDList: Array<string> = undefined
    return expect(instance.defaultCURDDelPhotoGroupByIDList(iDList, {})).resolves.toBe(null)
  })
  test("defaultCURDDelTimelineEventByIDList", () => {
    const iDList: Array<string> = undefined
    return expect(instance.defaultCURDDelTimelineEventByIDList(iDList, {})).resolves.toBe(null)
  })
  test("defaultCURDGetAppSettingList", () => {
    const keyList: Array<string> = undefined
    return expect(instance.defaultCURDGetAppSettingList(keyList, {})).resolves.toBe(null)
  })
  test("defaultCURDGetPhotoGroupList", () => {
    const iDList: Array<string> = undefined
    return expect(instance.defaultCURDGetPhotoGroupList(iDList, {})).resolves.toBe(null)
  })
  test("defaultCURDGetPhotoList", () => {
    const iDList: Array<string> = undefined
    return expect(instance.defaultCURDGetPhotoList(iDList, {})).resolves.toBe(null)
  })
  test("defaultCURDGetTimelineEventList", () => {
    const iDList: Array<string> = undefined
    return expect(instance.defaultCURDGetTimelineEventList(iDList, {})).resolves.toBe(null)
  })
  test("defaultCURDUpdateAppSetting", () => {
    const body: api.ApiUpdateAppSettingRequest = undefined
    return expect(instance.defaultCURDUpdateAppSetting(body, {})).resolves.toBe(null)
  })
  test("defaultCURDUpdatePhoto", () => {
    const body: api.ApiUpdatePhotoRequest = undefined
    return expect(instance.defaultCURDUpdatePhoto(body, {})).resolves.toBe(null)
  })
  test("defaultCURDUpdatePhotoGroup", () => {
    const body: api.ApiUpdatePhotoGroupRequest = undefined
    return expect(instance.defaultCURDUpdatePhotoGroup(body, {})).resolves.toBe(null)
  })
  test("defaultCURDUpdateTimelineEvent", () => {
    const body: api.ApiUpdateTimelineEventRequest = undefined
    return expect(instance.defaultCURDUpdateTimelineEvent(body, {})).resolves.toBe(null)
  })
})

describe("PhotoServiceApi", () => {
  let instance: api.PhotoServiceApi
  beforeEach(function() {
    instance = new api.PhotoServiceApi(config)
  });

  test("photoServiceDeletePhoto", () => {
    const id: string = "id_example"
    return expect(instance.photoServiceDeletePhoto(id, {})).resolves.toBe(null)
  })
  test("photoServiceGetBurstGroupsConfig", () => {
    return expect(instance.photoServiceGetBurstGroupsConfig({})).resolves.toBe(null)
  })
  test("photoServiceGetBurstGroupsStatus", () => {
    return expect(instance.photoServiceGetBurstGroupsStatus({})).resolves.toBe(null)
  })
  test("photoServiceGetPhotoDetail", () => {
    const id: string = "id_example"
    return expect(instance.photoServiceGetPhotoDetail(id, {})).resolves.toBe(null)
  })
  test("photoServiceGetPhotoStats", () => {
    return expect(instance.photoServiceGetPhotoStats({})).resolves.toBe(null)
  })
  test("photoServiceListPhotoSegments", () => {
    const timeline: string = "timeline_example"
    const tag: string = "tag_example"
    const keyword: string = "keyword_example"
    const brand: string = "brand_example"
    const lens: string = "lens_example"
    const focalMin: string = "focalMin_example"
    const focalMax: string = "focalMax_example"
    const isoMin: number = 56
    const isoMax: number = 56
    const shotAtStart: string = "shotAtStart_example"
    const shotAtEnd: string = "shotAtEnd_example"
    const sortBy: string = "sortBy_example"
    const sortOrder: string = "sortOrder_example"
    const burstGroupId: string = "burstGroupId_example"
    const burstProfile: string = "burstProfile_example"
    const segmentMode: string = "segmentMode_example"
    return expect(instance.photoServiceListPhotoSegments(timeline, tag, keyword, brand, lens, focalMin, focalMax, isoMin, isoMax, shotAtStart, shotAtEnd, sortBy, sortOrder, burstGroupId, burstProfile, segmentMode, {})).resolves.toBe(null)
  })
  test("photoServiceRebuildBurstGroups", () => {
    const body: api.ApiEmpty = undefined
    return expect(instance.photoServiceRebuildBurstGroups(body, {})).resolves.toBe(null)
  })
  test("photoServiceSearchPhotos", () => {
    const page: number = 56
    const pageSize: number = 56
    const timeline: string = "timeline_example"
    const tag: string = "tag_example"
    const keyword: string = "keyword_example"
    const brand: string = "brand_example"
    const lens: string = "lens_example"
    const focalMin: string = "focalMin_example"
    const focalMax: string = "focalMax_example"
    const isoMin: number = 56
    const isoMax: number = 56
    const shotAtStart: string = "shotAtStart_example"
    const shotAtEnd: string = "shotAtEnd_example"
    const sortBy: string = "sortBy_example"
    const sortOrder: string = "sortOrder_example"
    const burstGroupId: string = "burstGroupId_example"
    const burstProfile: string = "burstProfile_example"
    return expect(instance.photoServiceSearchPhotos(page, pageSize, timeline, tag, keyword, brand, lens, focalMin, focalMax, isoMin, isoMax, shotAtStart, shotAtEnd, sortBy, sortOrder, burstGroupId, burstProfile, {})).resolves.toBe(null)
  })
  test("photoServiceSetBurstGroupCover", () => {
    const body: api.ApiSetBurstGroupCoverRequest = undefined
    const groupId: string = "groupId_example"
    return expect(instance.photoServiceSetBurstGroupCover(body, groupId, {})).resolves.toBe(null)
  })
  test("photoServiceUpdateBurstGroupsConfig", () => {
    const body: api.ApiUpdateBurstGroupsConfigRequest = undefined
    return expect(instance.photoServiceUpdateBurstGroupsConfig(body, {})).resolves.toBe(null)
  })
  test("photoServiceUpdatePhotoTags", () => {
    const body: api.ApiUpdatePhotoTagsRequest = undefined
    const id: string = "id_example"
    return expect(instance.photoServiceUpdatePhotoTags(body, id, {})).resolves.toBe(null)
  })
})

describe("QueryServiceApi", () => {
  let instance: api.QueryServiceApi
  beforeEach(function() {
    instance = new api.QueryServiceApi(config)
  });

  test("queryServiceExecuteSQL", () => {
    const body: api.ApiExecuteSQLRequest = undefined
    return expect(instance.queryServiceExecuteSQL(body, {})).resolves.toBe(null)
  })
  test("queryServiceGetAttributeValues", () => {
    return expect(instance.queryServiceGetAttributeValues({})).resolves.toBe(null)
  })
  test("queryServiceGetPhotoSchema", () => {
    return expect(instance.queryServiceGetPhotoSchema({})).resolves.toBe(null)
  })
})

describe("TagServiceApi", () => {
  let instance: api.TagServiceApi
  beforeEach(function() {
    instance = new api.TagServiceApi(config)
  });

  test("tagServiceBindTags", () => {
    const body: api.ApiBindTagsRequest = undefined
    return expect(instance.tagServiceBindTags(body, {})).resolves.toBe(null)
  })
  test("tagServiceGetPhotosByTag", () => {
    const name: string = "name_example"
    return expect(instance.tagServiceGetPhotosByTag(name, {})).resolves.toBe(null)
  })
  test("tagServiceListTags", () => {
    return expect(instance.tagServiceListTags({})).resolves.toBe(null)
  })
  test("tagServiceUnbindTags", () => {
    const body: api.ApiUnbindTagsRequest = undefined
    return expect(instance.tagServiceUnbindTags(body, {})).resolves.toBe(null)
  })
})

describe("TimelineServiceApi", () => {
  let instance: api.TimelineServiceApi
  beforeEach(function() {
    instance = new api.TimelineServiceApi(config)
  });

  test("timelineServiceDeleteEvent", () => {
    const id: string = "id_example"
    return expect(instance.timelineServiceDeleteEvent(id, {})).resolves.toBe(null)
  })
  test("timelineServiceGetPhotosByTimeline", () => {
    const name: string = "name_example"
    return expect(instance.timelineServiceGetPhotosByTimeline(name, {})).resolves.toBe(null)
  })
  test("timelineServiceGetRecomputeTimelinesStatus", () => {
    return expect(instance.timelineServiceGetRecomputeTimelinesStatus({})).resolves.toBe(null)
  })
  test("timelineServiceListEvents", () => {
    return expect(instance.timelineServiceListEvents({})).resolves.toBe(null)
  })
  test("timelineServiceListTimelines", () => {
    return expect(instance.timelineServiceListTimelines({})).resolves.toBe(null)
  })
  test("timelineServiceRecomputeTimelines", () => {
    const body: api.ApiEmpty = undefined
    return expect(instance.timelineServiceRecomputeTimelines(body, {})).resolves.toBe(null)
  })
  test("timelineServiceSaveEvent", () => {
    const body: api.ApiSaveTimelineEventRequest = undefined
    return expect(instance.timelineServiceSaveEvent(body, {})).resolves.toBe(null)
  })
})

describe("VlmServiceApi", () => {
  let instance: api.VlmServiceApi
  beforeEach(function() {
    instance = new api.VlmServiceApi(config)
  });

  test("vlmServiceDescribePhoto", () => {
    const body: api.ApiDescribePhotoRequest = undefined
    const id: string = "id_example"
    return expect(instance.vlmServiceDescribePhoto(body, id, {})).resolves.toBe(null)
  })
  test("vlmServiceGetVlmQueueStatus", () => {
    return expect(instance.vlmServiceGetVlmQueueStatus({})).resolves.toBe(null)
  })
  test("vlmServiceStartVlmQueue", () => {
    const body: api.ApiStartVlmQueueRequest = undefined
    return expect(instance.vlmServiceStartVlmQueue(body, {})).resolves.toBe(null)
  })
  test("vlmServiceStopVlmQueue", () => {
    const body: api.ApiEmpty = undefined
    return expect(instance.vlmServiceStopVlmQueue(body, {})).resolves.toBe(null)
  })
})

