# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.vlm_service_api import VlmServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVlmServiceApi(unittest.TestCase):
    """VlmServiceApi unit test stubs"""

    def setUp(self):
        self.api = VlmServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_vlm_service_describe_photo(self):
        """Test case for vlm_service_describe_photo

        """
        pass

    def test_vlm_service_get_vlm_queue_status(self):
        """Test case for vlm_service_get_vlm_queue_status

        """
        pass

    def test_vlm_service_start_vlm_queue(self):
        """Test case for vlm_service_start_vlm_queue

        """
        pass

    def test_vlm_service_stop_vlm_queue(self):
        """Test case for vlm_service_stop_vlm_queue

        """
        pass


if __name__ == '__main__':
    unittest.main()
