# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tag_service_api import TagServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTagServiceApi(unittest.TestCase):
    """TagServiceApi unit test stubs"""

    def setUp(self):
        self.api = TagServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tag_service_bind_tags(self):
        """Test case for tag_service_bind_tags

        """
        pass

    def test_tag_service_get_photos_by_tag(self):
        """Test case for tag_service_get_photos_by_tag

        """
        pass

    def test_tag_service_list_tags(self):
        """Test case for tag_service_list_tags

        """
        pass

    def test_tag_service_unbind_tags(self):
        """Test case for tag_service_unbind_tags

        """
        pass


if __name__ == '__main__':
    unittest.main()
