# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.abandon_code_curd_api import AbandonCodeCURDApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAbandonCodeCURDApi(unittest.TestCase):
    """AbandonCodeCURDApi unit test stubs"""

    def setUp(self):
        self.api = AbandonCodeCURDApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_abandon_code_curd_add_abandon_code(self):
        """Test case for abandon_code_curd_add_abandon_code

        """
        pass

    def test_abandon_code_curd_del_abandon_code_by_idx1_list(self):
        """Test case for abandon_code_curd_del_abandon_code_by_idx1_list

        """
        pass

    def test_abandon_code_curd_get_abandon_code_list(self):
        """Test case for abandon_code_curd_get_abandon_code_list

        """
        pass

    def test_abandon_code_curd_update_abandon_code(self):
        """Test case for abandon_code_curd_update_abandon_code

        """
        pass


if __name__ == '__main__':
    unittest.main()
