# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.photo_service_api import PhotoServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPhotoServiceApi(unittest.TestCase):
    """PhotoServiceApi unit test stubs"""

    def setUp(self):
        self.api = PhotoServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_photo_service_delete_photo(self):
        """Test case for photo_service_delete_photo

        """
        pass

    def test_photo_service_get_photo_detail(self):
        """Test case for photo_service_get_photo_detail

        """
        pass

    def test_photo_service_get_photo_stats(self):
        """Test case for photo_service_get_photo_stats

        """
        pass

    def test_photo_service_search_photos(self):
        """Test case for photo_service_search_photos

        """
        pass

    def test_photo_service_update_photo_tags(self):
        """Test case for photo_service_update_photo_tags

        """
        pass


if __name__ == '__main__':
    unittest.main()
