# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.query_service_api import QueryServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestQueryServiceApi(unittest.TestCase):
    """QueryServiceApi unit test stubs"""

    def setUp(self):
        self.api = QueryServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_query_service_execute_sql(self):
        """Test case for query_service_execute_sql

        """
        pass

    def test_query_service_get_attribute_values(self):
        """Test case for query_service_get_attribute_values

        """
        pass

    def test_query_service_get_photo_schema(self):
        """Test case for query_service_get_photo_schema

        """
        pass


if __name__ == '__main__':
    unittest.main()
