// Code generated by tools/genCURD. DO NOT EDIT.

package service

import (
	api "backend/internal/pkg/api"

	"github.com/go-kratos/kratos/v2/transport/grpc"
	"github.com/go-kratos/kratos/v2/transport/http"
)

type DefaultCURDServer struct {
	api.UnimplementedDefaultCURDServer
}

func (s *DefaultCURDServer) Reg(grpcSrv *grpc.Server, httpSrv *http.Server) {
	if grpcSrv != nil {
		api.RegisterDefaultCURDServer(grpcSrv, s)
	}
	if httpSrv != nil {
		api.RegisterDefaultCURDHTTPServer(httpSrv, s)
	}
}
