// Code generated by tools/genCURD. DO NOT EDIT.

package service

import "time"

import (
	"context"

	"backend/internal/defaultService/data"
	"backend/internal/pkg/api"

	"github.com/pancake-lee/pgo/pkg/papp"
)

func DO2DTO_Photo(do *data.PhotoDO) *api.PhotoInfo {
	if do == nil {
		return nil
	}
	return &api.PhotoInfo{
        ID: do.ID,
        Filename: do.Filename,
        FilePath: do.FilePath,
        Timeline: do.Timeline,
        Tags: do.Tags,
        Description: do.Description,
        Objects: do.Objects,
        Colors: do.Colors,
        Scene: do.Scene,
        Lighting: do.Lighting,
        Mood: do.Mood,
        Composition: do.Composition,
        ShotAt: do.ShotAt.Unix(),
        Width: do.Width,
        Height: do.Height,
        Brand: do.Brand,
        Model: do.Model,
        Lens: do.Lens,
        FocalLength: do.FocalLength,
        Aperture: do.Aperture,
        Iso: do.Iso,
        ExposureTime: do.ExposureTime,
        Latitude: do.Latitude,
        Longitude: do.Longitude,
        Altitude: do.Altitude,
        ImportedAt: do.ImportedAt.Unix(),
	}
}
func DTO2DO_Photo(dto *api.PhotoInfo) *data.PhotoDO {
	if dto == nil {
		return nil
	}
	return &data.PhotoDO{
        ID: dto.ID,
        Filename: dto.Filename,
        FilePath: dto.FilePath,
        Timeline: dto.Timeline,
        Tags: dto.Tags,
        Description: dto.Description,
        Objects: dto.Objects,
        Colors: dto.Colors,
        Scene: dto.Scene,
        Lighting: dto.Lighting,
        Mood: dto.Mood,
        Composition: dto.Composition,
        ShotAt: time.Unix(dto.ShotAt, 0),
        Width: dto.Width,
        Height: dto.Height,
        Brand: dto.Brand,
        Model: dto.Model,
        Lens: dto.Lens,
        FocalLength: dto.FocalLength,
        Aperture: dto.Aperture,
        Iso: dto.Iso,
        ExposureTime: dto.ExposureTime,
        Latitude: dto.Latitude,
        Longitude: dto.Longitude,
        Altitude: dto.Altitude,
        ImportedAt: time.Unix(dto.ImportedAt, 0),
	}
}

func (s *DefaultCURDServer) AddPhoto(
	_ctx context.Context, req *api.AddPhotoRequest,
) (resp *api.AddPhotoResponse, err error) {
	ctx := papp.NewAppCtx(_ctx)

	if req.Photo == nil {
		return nil, api.ErrorInvalidArgument("")
	}
	newData := DTO2DO_Photo(req.Photo)

	err = data.PhotoDAO.Add(ctx, newData)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}

	ctx.Log.Debugf("AddPhoto: %v", newData.ID)

	resp = new(api.AddPhotoResponse)
	resp.Photo = DO2DTO_Photo(newData)
	return resp, nil
}

func (s *DefaultCURDServer) GetPhotoList(
	_ctx context.Context, req *api.GetPhotoListRequest,
) (resp *api.GetPhotoListResponse, err error) {
	ctx := papp.NewAppCtx(_ctx)

	var dataList []*data.PhotoDO

	if len(req.IDList) != 0 {
		ctx.Log.Debugf("GetPhotoList: %v", req.IDList)

		dataList, err = data.PhotoDAO.GetByIndex(ctx,
            req.IDList,
		)
		if err != nil {
			return nil, ctx.Log.LogErr(err)
		}
	} else {

		dataList, err = data.PhotoDAO.GetAll(ctx)
		if err != nil {
			return nil, ctx.Log.LogErr(err)
		}

	}

	ctx.Log.Debugf("GetPhotoList resp len %v", len(dataList))

	resp = new(api.GetPhotoListResponse)
	resp.PhotoList = make([]*api.PhotoInfo, 0, len(dataList))
	for _, data := range dataList {
		resp.PhotoList = append(resp.PhotoList, DO2DTO_Photo(data))
	}
	return resp, nil
}


func (s *DefaultCURDServer) UpdatePhoto(
	_ctx context.Context, req *api.UpdatePhotoRequest,
) (resp *api.UpdatePhotoResponse, err error) {
	ctx := papp.NewAppCtx(_ctx)

	if req.Photo == nil {
		return nil, api.ErrorInvalidArgument("")
	}

	do := DTO2DO_Photo(req.Photo)
	err = data.PhotoDAO.UpdateByID(ctx, do)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	ctx.Log.Debugf("UpdatePhoto %v", req.Photo.ID)

	resp = new(api.UpdatePhotoResponse)
	d, err := data.PhotoDAO.GetByID(ctx, req.Photo.ID)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	resp.Photo = DO2DTO_Photo(d)
	return resp, nil
}

func (s *DefaultCURDServer) DelPhotoByIDList(
	_ctx context.Context, req *api.DelPhotoByIDListRequest,
) (resp *api.Empty, err error) {
	ctx := papp.NewAppCtx(_ctx)

	if len(req.IDList) == 0 {
		return nil, nil
	}
	err = data.PhotoDAO.DelByIDList(ctx, req.IDList)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	ctx.Log.Debugf("DelPhotoByIDList %v", req.IDList)
	return nil, nil
}

