// Code generated by tools/genCURD. DO NOT EDIT.

package service

import "time"

import (
	"context"

	"backend/internal/defaultService/data"
	"backend/internal/pkg/api"

	"github.com/pancake-lee/pgo/pkg/papp"
)

func DO2DTO_PhotoGroup(do *data.PhotoGroupDO) *api.PhotoGroupInfo {
	if do == nil {
		return nil
	}
	return &api.PhotoGroupInfo{
        ID: do.ID,
        CoverPhotoID: do.CoverPhotoID,
        PhotoCount: do.PhotoCount,
        TimeStart: do.TimeStart.Unix(),
        TimeEnd: do.TimeEnd.Unix(),
        HashMax: do.HashMax,
        CreatedAt: do.CreatedAt.Unix(),
	}
}
func DTO2DO_PhotoGroup(dto *api.PhotoGroupInfo) *data.PhotoGroupDO {
	if dto == nil {
		return nil
	}
	return &data.PhotoGroupDO{
        ID: dto.ID,
        CoverPhotoID: dto.CoverPhotoID,
        PhotoCount: dto.PhotoCount,
        TimeStart: time.Unix(dto.TimeStart, 0),
        TimeEnd: time.Unix(dto.TimeEnd, 0),
        HashMax: dto.HashMax,
        CreatedAt: time.Unix(dto.CreatedAt, 0),
	}
}

func (s *DefaultCURDServer) AddPhotoGroup(
	_ctx context.Context, req *api.AddPhotoGroupRequest,
) (resp *api.AddPhotoGroupResponse, err error) {
	ctx := papp.NewAppCtx(_ctx)

	if req.PhotoGroup == nil {
		return nil, api.ErrorInvalidArgument("")
	}
	newData := DTO2DO_PhotoGroup(req.PhotoGroup)

	err = data.PhotoGroupDAO.Add(ctx, newData)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}

	ctx.Log.Debugf("AddPhotoGroup: %v", newData.ID)

	resp = new(api.AddPhotoGroupResponse)
	resp.PhotoGroup = DO2DTO_PhotoGroup(newData)
	return resp, nil
}

func (s *DefaultCURDServer) GetPhotoGroupList(
	_ctx context.Context, req *api.GetPhotoGroupListRequest,
) (resp *api.GetPhotoGroupListResponse, err error) {
	ctx := papp.NewAppCtx(_ctx)

	var dataList []*data.PhotoGroupDO

	if len(req.IDList) != 0 {
		ctx.Log.Debugf("GetPhotoGroupList: %v", req.IDList)

		dataList, err = data.PhotoGroupDAO.GetByIndex(ctx,
            req.IDList,
		)
		if err != nil {
			return nil, ctx.Log.LogErr(err)
		}
	} else {

		dataList, err = data.PhotoGroupDAO.GetAll(ctx)
		if err != nil {
			return nil, ctx.Log.LogErr(err)
		}

	}

	ctx.Log.Debugf("GetPhotoGroupList resp len %v", len(dataList))

	resp = new(api.GetPhotoGroupListResponse)
	resp.PhotoGroupList = make([]*api.PhotoGroupInfo, 0, len(dataList))
	for _, data := range dataList {
		resp.PhotoGroupList = append(resp.PhotoGroupList, DO2DTO_PhotoGroup(data))
	}
	return resp, nil
}


func (s *DefaultCURDServer) UpdatePhotoGroup(
	_ctx context.Context, req *api.UpdatePhotoGroupRequest,
) (resp *api.UpdatePhotoGroupResponse, err error) {
	ctx := papp.NewAppCtx(_ctx)

	if req.PhotoGroup == nil {
		return nil, api.ErrorInvalidArgument("")
	}

	do := DTO2DO_PhotoGroup(req.PhotoGroup)
	err = data.PhotoGroupDAO.UpdateByID(ctx, do)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	ctx.Log.Debugf("UpdatePhotoGroup %v", req.PhotoGroup.ID)

	resp = new(api.UpdatePhotoGroupResponse)
	d, err := data.PhotoGroupDAO.GetByID(ctx, req.PhotoGroup.ID)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	resp.PhotoGroup = DO2DTO_PhotoGroup(d)
	return resp, nil
}

func (s *DefaultCURDServer) DelPhotoGroupByIDList(
	_ctx context.Context, req *api.DelPhotoGroupByIDListRequest,
) (resp *api.Empty, err error) {
	ctx := papp.NewAppCtx(_ctx)

	if len(req.IDList) == 0 {
		return nil, nil
	}
	err = data.PhotoGroupDAO.DelByIDList(ctx, req.IDList)
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	ctx.Log.Debugf("DelPhotoGroupByIDList %v", req.IDList)
	return nil, nil
}

