syntax = "proto3";
package api;
import "google/api/annotations.proto";
import "common.proto";
import "photo_service.proto";
option go_package = "backend-new/internal/pkg/api;api";

// TimelineService 时间线服务
service TimelineService {
    // 所有时间线列表
    rpc ListTimelines (Empty) returns (ListTimelinesResponse) {
        option (google.api.http) = {
            get: "/api/v1/timelines"
        };
    }
    // 某时间线下的照片
    rpc GetPhotosByTimeline (GetPhotosByTimelineRequest) returns (GetPhotosByTimelineResponse) {
        option (google.api.http) = {
            get: "/api/v1/timelines/{name}/photos"
        };
    }
}

// --------------------------------------------------
// ListTimelines

message ListTimelinesResponse {
    repeated string timelines = 1;
}

// --------------------------------------------------
// GetPhotosByTimeline

message GetPhotosByTimelineRequest {
    string name = 1;
}

message GetPhotosByTimelineResponse {
    string timeline = 1;
    repeated PhotoItem items = 2;
    int32 total = 3;
}
