// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: abandonCode.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------------------------------------------
// tbl : abandon_code
type AbandonCodeInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MARK REPLACE PB COL START 替换内容，所有字段
	Idx1          int32  `protobuf:"varint,1,opt,name=idx1,proto3" json:"idx1,omitempty"`
	Col1          string `protobuf:"bytes,2,opt,name=col1,proto3" json:"col1,omitempty"` // MARK REPLACE PB COL END
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbandonCodeInfo) Reset() {
	*x = AbandonCodeInfo{}
	mi := &file_abandonCode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonCodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonCodeInfo) ProtoMessage() {}

func (x *AbandonCodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_abandonCode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonCodeInfo.ProtoReflect.Descriptor instead.
func (*AbandonCodeInfo) Descriptor() ([]byte, []int) {
	return file_abandonCode_proto_rawDescGZIP(), []int{0}
}

func (x *AbandonCodeInfo) GetIdx1() int32 {
	if x != nil {
		return x.Idx1
	}
	return 0
}

func (x *AbandonCodeInfo) GetCol1() string {
	if x != nil {
		return x.Col1
	}
	return ""
}

type AddAbandonCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AbandonCode   *AbandonCodeInfo       `protobuf:"bytes,1,opt,name=abandon_code,json=abandonCode,proto3" json:"abandon_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAbandonCodeRequest) Reset() {
	*x = AddAbandonCodeRequest{}
	mi := &file_abandonCode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAbandonCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAbandonCodeRequest) ProtoMessage() {}

func (x *AddAbandonCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_abandonCode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAbandonCodeRequest.ProtoReflect.Descriptor instead.
func (*AddAbandonCodeRequest) Descriptor() ([]byte, []int) {
	return file_abandonCode_proto_rawDescGZIP(), []int{1}
}

func (x *AddAbandonCodeRequest) GetAbandonCode() *AbandonCodeInfo {
	if x != nil {
		return x.AbandonCode
	}
	return nil
}

type AddAbandonCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AbandonCode   *AbandonCodeInfo       `protobuf:"bytes,1,opt,name=abandon_code,json=abandonCode,proto3" json:"abandon_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAbandonCodeResponse) Reset() {
	*x = AddAbandonCodeResponse{}
	mi := &file_abandonCode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAbandonCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAbandonCodeResponse) ProtoMessage() {}

func (x *AddAbandonCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_abandonCode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAbandonCodeResponse.ProtoReflect.Descriptor instead.
func (*AddAbandonCodeResponse) Descriptor() ([]byte, []int) {
	return file_abandonCode_proto_rawDescGZIP(), []int{2}
}

func (x *AddAbandonCodeResponse) GetAbandonCode() *AbandonCodeInfo {
	if x != nil {
		return x.AbandonCode
	}
	return nil
}

type GetAbandonCodeListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MARK REPLACE IDX COL START 替换内容，索引字段
	Idx1List      []int32 `protobuf:"varint,1,rep,packed,name=idx1List,proto3" json:"idx1List,omitempty"`
	Idx2List      []int32 `protobuf:"varint,2,rep,packed,name=idx2List,proto3" json:"idx2List,omitempty"`
	Idx3List      []int32 `protobuf:"varint,3,rep,packed,name=idx3List,proto3" json:"idx3List,omitempty"` // MARK REPLACE IDX COL END
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAbandonCodeListRequest) Reset() {
	*x = GetAbandonCodeListRequest{}
	mi := &file_abandonCode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAbandonCodeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbandonCodeListRequest) ProtoMessage() {}

func (x *GetAbandonCodeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_abandonCode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbandonCodeListRequest.ProtoReflect.Descriptor instead.
func (*GetAbandonCodeListRequest) Descriptor() ([]byte, []int) {
	return file_abandonCode_proto_rawDescGZIP(), []int{3}
}

func (x *GetAbandonCodeListRequest) GetIdx1List() []int32 {
	if x != nil {
		return x.Idx1List
	}
	return nil
}

func (x *GetAbandonCodeListRequest) GetIdx2List() []int32 {
	if x != nil {
		return x.Idx2List
	}
	return nil
}

func (x *GetAbandonCodeListRequest) GetIdx3List() []int32 {
	if x != nil {
		return x.Idx3List
	}
	return nil
}

type GetAbandonCodeListResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AbandonCodeList []*AbandonCodeInfo     `protobuf:"bytes,1,rep,name=abandonCodeList,proto3" json:"abandonCodeList,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAbandonCodeListResponse) Reset() {
	*x = GetAbandonCodeListResponse{}
	mi := &file_abandonCode_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAbandonCodeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbandonCodeListResponse) ProtoMessage() {}

func (x *GetAbandonCodeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_abandonCode_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbandonCodeListResponse.ProtoReflect.Descriptor instead.
func (*GetAbandonCodeListResponse) Descriptor() ([]byte, []int) {
	return file_abandonCode_proto_rawDescGZIP(), []int{4}
}

func (x *GetAbandonCodeListResponse) GetAbandonCodeList() []*AbandonCodeInfo {
	if x != nil {
		return x.AbandonCodeList
	}
	return nil
}

// MARK REMOVE IF NO PRIMARY KEY START
type UpdateAbandonCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AbandonCode   *AbandonCodeInfo       `protobuf:"bytes,1,opt,name=abandonCode,proto3" json:"abandonCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAbandonCodeRequest) Reset() {
	*x = UpdateAbandonCodeRequest{}
	mi := &file_abandonCode_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAbandonCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAbandonCodeRequest) ProtoMessage() {}

func (x *UpdateAbandonCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_abandonCode_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAbandonCodeRequest.ProtoReflect.Descriptor instead.
func (*UpdateAbandonCodeRequest) Descriptor() ([]byte, []int) {
	return file_abandonCode_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAbandonCodeRequest) GetAbandonCode() *AbandonCodeInfo {
	if x != nil {
		return x.AbandonCode
	}
	return nil
}

type UpdateAbandonCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AbandonCode   *AbandonCodeInfo       `protobuf:"bytes,1,opt,name=abandonCode,proto3" json:"abandonCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAbandonCodeResponse) Reset() {
	*x = UpdateAbandonCodeResponse{}
	mi := &file_abandonCode_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAbandonCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAbandonCodeResponse) ProtoMessage() {}

func (x *UpdateAbandonCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_abandonCode_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAbandonCodeResponse.ProtoReflect.Descriptor instead.
func (*UpdateAbandonCodeResponse) Descriptor() ([]byte, []int) {
	return file_abandonCode_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAbandonCodeResponse) GetAbandonCode() *AbandonCodeInfo {
	if x != nil {
		return x.AbandonCode
	}
	return nil
}

type DelAbandonCodeByIdx1ListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MARK REPLACE PRIMARY IDX START
	Idx1List      []int32 `protobuf:"varint,1,rep,packed,name=idx1List,proto3" json:"idx1List,omitempty"` // MARK REPLACE PRIMARY IDX END
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelAbandonCodeByIdx1ListRequest) Reset() {
	*x = DelAbandonCodeByIdx1ListRequest{}
	mi := &file_abandonCode_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelAbandonCodeByIdx1ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelAbandonCodeByIdx1ListRequest) ProtoMessage() {}

func (x *DelAbandonCodeByIdx1ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_abandonCode_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelAbandonCodeByIdx1ListRequest.ProtoReflect.Descriptor instead.
func (*DelAbandonCodeByIdx1ListRequest) Descriptor() ([]byte, []int) {
	return file_abandonCode_proto_rawDescGZIP(), []int{7}
}

func (x *DelAbandonCodeByIdx1ListRequest) GetIdx1List() []int32 {
	if x != nil {
		return x.Idx1List
	}
	return nil
}

var File_abandonCode_proto protoreflect.FileDescriptor

const file_abandonCode_proto_rawDesc = "" +
	"\n" +
	"\x11abandonCode.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\fcommon.proto\"9\n" +
	"\x0fAbandonCodeInfo\x12\x12\n" +
	"\x04idx1\x18\x01 \x01(\x05R\x04idx1\x12\x12\n" +
	"\x04col1\x18\x02 \x01(\tR\x04col1\"P\n" +
	"\x15AddAbandonCodeRequest\x127\n" +
	"\fabandon_code\x18\x01 \x01(\v2\x14.api.AbandonCodeInfoR\vabandonCode\"Q\n" +
	"\x16AddAbandonCodeResponse\x127\n" +
	"\fabandon_code\x18\x01 \x01(\v2\x14.api.AbandonCodeInfoR\vabandonCode\"o\n" +
	"\x19GetAbandonCodeListRequest\x12\x1a\n" +
	"\bidx1List\x18\x01 \x03(\x05R\bidx1List\x12\x1a\n" +
	"\bidx2List\x18\x02 \x03(\x05R\bidx2List\x12\x1a\n" +
	"\bidx3List\x18\x03 \x03(\x05R\bidx3List\"\\\n" +
	"\x1aGetAbandonCodeListResponse\x12>\n" +
	"\x0fabandonCodeList\x18\x01 \x03(\v2\x14.api.AbandonCodeInfoR\x0fabandonCodeList\"R\n" +
	"\x18UpdateAbandonCodeRequest\x126\n" +
	"\vabandonCode\x18\x01 \x01(\v2\x14.api.AbandonCodeInfoR\vabandonCode\"S\n" +
	"\x19UpdateAbandonCodeResponse\x126\n" +
	"\vabandonCode\x18\x01 \x01(\v2\x14.api.AbandonCodeInfoR\vabandonCode\"=\n" +
	"\x1fDelAbandonCodeByIdx1ListRequest\x12\x1a\n" +
	"\bidx1List\x18\x01 \x03(\x05R\bidx1List2\xb7\x03\n" +
	"\x0fabandonCodeCURD\x12c\n" +
	"\x0eAddAbandonCode\x12\x1a.api.AddAbandonCodeRequest\x1a\x1b.api.AddAbandonCodeResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/abandon-code\x12l\n" +
	"\x12GetAbandonCodeList\x12\x1e.api.GetAbandonCodeListRequest\x1a\x1f.api.GetAbandonCodeListResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/abandon-code\x12l\n" +
	"\x11UpdateAbandonCode\x12\x1d.api.UpdateAbandonCodeRequest\x1a\x1e.api.UpdateAbandonCodeResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*2\r/abandon-code\x12c\n" +
	"\x18DelAbandonCodeByIdx1List\x12$.api.DelAbandonCodeByIdx1ListRequest\x1a\n" +
	".api.Empty\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/abandon-codeB\"Z backend-new/internal/pkg/api;apib\x06proto3"

var (
	file_abandonCode_proto_rawDescOnce sync.Once
	file_abandonCode_proto_rawDescData []byte
)

func file_abandonCode_proto_rawDescGZIP() []byte {
	file_abandonCode_proto_rawDescOnce.Do(func() {
		file_abandonCode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_abandonCode_proto_rawDesc), len(file_abandonCode_proto_rawDesc)))
	})
	return file_abandonCode_proto_rawDescData
}

var file_abandonCode_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_abandonCode_proto_goTypes = []any{
	(*AbandonCodeInfo)(nil),                 // 0: api.AbandonCodeInfo
	(*AddAbandonCodeRequest)(nil),           // 1: api.AddAbandonCodeRequest
	(*AddAbandonCodeResponse)(nil),          // 2: api.AddAbandonCodeResponse
	(*GetAbandonCodeListRequest)(nil),       // 3: api.GetAbandonCodeListRequest
	(*GetAbandonCodeListResponse)(nil),      // 4: api.GetAbandonCodeListResponse
	(*UpdateAbandonCodeRequest)(nil),        // 5: api.UpdateAbandonCodeRequest
	(*UpdateAbandonCodeResponse)(nil),       // 6: api.UpdateAbandonCodeResponse
	(*DelAbandonCodeByIdx1ListRequest)(nil), // 7: api.DelAbandonCodeByIdx1ListRequest
	(*Empty)(nil),                           // 8: api.Empty
}
var file_abandonCode_proto_depIdxs = []int32{
	0, // 0: api.AddAbandonCodeRequest.abandon_code:type_name -> api.AbandonCodeInfo
	0, // 1: api.AddAbandonCodeResponse.abandon_code:type_name -> api.AbandonCodeInfo
	0, // 2: api.GetAbandonCodeListResponse.abandonCodeList:type_name -> api.AbandonCodeInfo
	0, // 3: api.UpdateAbandonCodeRequest.abandonCode:type_name -> api.AbandonCodeInfo
	0, // 4: api.UpdateAbandonCodeResponse.abandonCode:type_name -> api.AbandonCodeInfo
	1, // 5: api.abandonCodeCURD.AddAbandonCode:input_type -> api.AddAbandonCodeRequest
	3, // 6: api.abandonCodeCURD.GetAbandonCodeList:input_type -> api.GetAbandonCodeListRequest
	5, // 7: api.abandonCodeCURD.UpdateAbandonCode:input_type -> api.UpdateAbandonCodeRequest
	7, // 8: api.abandonCodeCURD.DelAbandonCodeByIdx1List:input_type -> api.DelAbandonCodeByIdx1ListRequest
	2, // 9: api.abandonCodeCURD.AddAbandonCode:output_type -> api.AddAbandonCodeResponse
	4, // 10: api.abandonCodeCURD.GetAbandonCodeList:output_type -> api.GetAbandonCodeListResponse
	6, // 11: api.abandonCodeCURD.UpdateAbandonCode:output_type -> api.UpdateAbandonCodeResponse
	8, // 12: api.abandonCodeCURD.DelAbandonCodeByIdx1List:output_type -> api.Empty
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_abandonCode_proto_init() }
func file_abandonCode_proto_init() {
	if File_abandonCode_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_abandonCode_proto_rawDesc), len(file_abandonCode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_abandonCode_proto_goTypes,
		DependencyIndexes: file_abandonCode_proto_depIdxs,
		MessageInfos:      file_abandonCode_proto_msgTypes,
	}.Build()
	File_abandonCode_proto = out.File
	file_abandonCode_proto_goTypes = nil
	file_abandonCode_proto_depIdxs = nil
}
