// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: error_reason.proto

package api

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_Unknown         ErrorReason = 0 // 未知错误
	ErrorReason_InvalidArgument ErrorReason = 1 // 请求参数错误
	ErrorReason_Unauthorized    ErrorReason = 2 // 未授权
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "Unknown",
		1: "InvalidArgument",
		2: "Unauthorized",
	}
	ErrorReason_value = map[string]int32{
		"Unknown":         0,
		"InvalidArgument": 1,
		"Unauthorized":    2,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_error_reason_proto protoreflect.FileDescriptor

const file_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x12error_reason.proto\x12\x03api\x1a\x13errors/errors.proto*Y\n" +
	"\vErrorReason\x12\x11\n" +
	"\aUnknown\x10\x00\x1a\x04\xa8E\xf4\x03\x12\x19\n" +
	"\x0fInvalidArgument\x10\x01\x1a\x04\xa8E\x90\x03\x12\x16\n" +
	"\fUnauthorized\x10\x02\x1a\x04\xa8E\x91\x03\x1a\x04\xa0E\xf4\x03B\"Z backend-new/internal/pkg/api;apib\x06proto3"

var (
	file_error_reason_proto_rawDescOnce sync.Once
	file_error_reason_proto_rawDescData []byte
)

func file_error_reason_proto_rawDescGZIP() []byte {
	file_error_reason_proto_rawDescOnce.Do(func() {
		file_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_error_reason_proto_rawDesc), len(file_error_reason_proto_rawDesc)))
	})
	return file_error_reason_proto_rawDescData
}

var file_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.ErrorReason
}
var file_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_error_reason_proto_init() }
func file_error_reason_proto_init() {
	if File_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_error_reason_proto_rawDesc), len(file_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_reason_proto_goTypes,
		DependencyIndexes: file_error_reason_proto_depIdxs,
		EnumInfos:         file_error_reason_proto_enumTypes,
	}.Build()
	File_error_reason_proto = out.File
	file_error_reason_proto_goTypes = nil
	file_error_reason_proto_depIdxs = nil
}
