// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: query_service.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteSQLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteSQLRequest) Reset() {
	*x = ExecuteSQLRequest{}
	mi := &file_query_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSQLRequest) ProtoMessage() {}

func (x *ExecuteSQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSQLRequest.ProtoReflect.Descriptor instead.
func (*ExecuteSQLRequest) Descriptor() ([]byte, []int) {
	return file_query_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteSQLRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *ExecuteSQLRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ExecuteSQLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*structpb.Struct     `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteSQLResponse) Reset() {
	*x = ExecuteSQLResponse{}
	mi := &file_query_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSQLResponse) ProtoMessage() {}

func (x *ExecuteSQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSQLResponse.ProtoReflect.Descriptor instead.
func (*ExecuteSQLResponse) Descriptor() ([]byte, []int) {
	return file_query_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteSQLResponse) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *ExecuteSQLResponse) GetRows() []*structpb.Struct {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ExecuteSQLResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SchemaField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GoType        string                 `protobuf:"bytes,2,opt,name=go_type,json=goType,proto3" json:"go_type,omitempty"`
	SqlType       string                 `protobuf:"bytes,3,opt,name=sql_type,json=sqlType,proto3" json:"sql_type,omitempty"`
	JsonTag       string                 `protobuf:"bytes,4,opt,name=json_tag,json=jsonTag,proto3" json:"json_tag,omitempty"`
	GormTag       string                 `protobuf:"bytes,5,opt,name=gorm_tag,json=gormTag,proto3" json:"gorm_tag,omitempty"`
	Nullable      bool                   `protobuf:"varint,6,opt,name=nullable,proto3" json:"nullable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaField) Reset() {
	*x = SchemaField{}
	mi := &file_query_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaField) ProtoMessage() {}

func (x *SchemaField) ProtoReflect() protoreflect.Message {
	mi := &file_query_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaField.ProtoReflect.Descriptor instead.
func (*SchemaField) Descriptor() ([]byte, []int) {
	return file_query_service_proto_rawDescGZIP(), []int{2}
}

func (x *SchemaField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchemaField) GetGoType() string {
	if x != nil {
		return x.GoType
	}
	return ""
}

func (x *SchemaField) GetSqlType() string {
	if x != nil {
		return x.SqlType
	}
	return ""
}

func (x *SchemaField) GetJsonTag() string {
	if x != nil {
		return x.JsonTag
	}
	return ""
}

func (x *SchemaField) GetGormTag() string {
	if x != nil {
		return x.GormTag
	}
	return ""
}

func (x *SchemaField) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

type GetPhotoSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Fields        []*SchemaField         `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPhotoSchemaResponse) Reset() {
	*x = GetPhotoSchemaResponse{}
	mi := &file_query_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhotoSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhotoSchemaResponse) ProtoMessage() {}

func (x *GetPhotoSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhotoSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetPhotoSchemaResponse) Descriptor() ([]byte, []int) {
	return file_query_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetPhotoSchemaResponse) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *GetPhotoSchemaResponse) GetFields() []*SchemaField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type AttributeValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []string               `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	Colors        []string               `protobuf:"bytes,2,rep,name=colors,proto3" json:"colors,omitempty"`
	Scene         []string               `protobuf:"bytes,3,rep,name=scene,proto3" json:"scene,omitempty"`
	Lighting      []string               `protobuf:"bytes,4,rep,name=lighting,proto3" json:"lighting,omitempty"`
	Mood          []string               `protobuf:"bytes,5,rep,name=mood,proto3" json:"mood,omitempty"`
	Composition   []string               `protobuf:"bytes,6,rep,name=composition,proto3" json:"composition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeValues) Reset() {
	*x = AttributeValues{}
	mi := &file_query_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValues) ProtoMessage() {}

func (x *AttributeValues) ProtoReflect() protoreflect.Message {
	mi := &file_query_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValues.ProtoReflect.Descriptor instead.
func (*AttributeValues) Descriptor() ([]byte, []int) {
	return file_query_service_proto_rawDescGZIP(), []int{4}
}

func (x *AttributeValues) GetObjects() []string {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *AttributeValues) GetColors() []string {
	if x != nil {
		return x.Colors
	}
	return nil
}

func (x *AttributeValues) GetScene() []string {
	if x != nil {
		return x.Scene
	}
	return nil
}

func (x *AttributeValues) GetLighting() []string {
	if x != nil {
		return x.Lighting
	}
	return nil
}

func (x *AttributeValues) GetMood() []string {
	if x != nil {
		return x.Mood
	}
	return nil
}

func (x *AttributeValues) GetComposition() []string {
	if x != nil {
		return x.Composition
	}
	return nil
}

type GetAttributeValuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        *AttributeValues       `protobuf:"bytes,1,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributeValuesResponse) Reset() {
	*x = GetAttributeValuesResponse{}
	mi := &file_query_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributeValuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributeValuesResponse) ProtoMessage() {}

func (x *GetAttributeValuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributeValuesResponse.ProtoReflect.Descriptor instead.
func (*GetAttributeValuesResponse) Descriptor() ([]byte, []int) {
	return file_query_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetAttributeValuesResponse) GetValues() *AttributeValues {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_query_service_proto protoreflect.FileDescriptor

const file_query_service_proto_rawDesc = "" +
	"\n" +
	"\x13query_service.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\fcommon.proto\";\n" +
	"\x11ExecuteSQLRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"q\n" +
	"\x12ExecuteSQLResponse\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12+\n" +
	"\x04rows\x18\x02 \x03(\v2\x17.google.protobuf.StructR\x04rows\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\xa7\x01\n" +
	"\vSchemaField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\ago_type\x18\x02 \x01(\tR\x06goType\x12\x19\n" +
	"\bsql_type\x18\x03 \x01(\tR\asqlType\x12\x19\n" +
	"\bjson_tag\x18\x04 \x01(\tR\ajsonTag\x12\x19\n" +
	"\bgorm_tag\x18\x05 \x01(\tR\agormTag\x12\x1a\n" +
	"\bnullable\x18\x06 \x01(\bR\bnullable\"a\n" +
	"\x16GetPhotoSchemaResponse\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12(\n" +
	"\x06fields\x18\x02 \x03(\v2\x10.api.SchemaFieldR\x06fields\"\xab\x01\n" +
	"\x0fAttributeValues\x12\x18\n" +
	"\aobjects\x18\x01 \x03(\tR\aobjects\x12\x16\n" +
	"\x06colors\x18\x02 \x03(\tR\x06colors\x12\x14\n" +
	"\x05scene\x18\x03 \x03(\tR\x05scene\x12\x1a\n" +
	"\blighting\x18\x04 \x03(\tR\blighting\x12\x12\n" +
	"\x04mood\x18\x05 \x03(\tR\x04mood\x12 \n" +
	"\vcomposition\x18\x06 \x03(\tR\vcomposition\"J\n" +
	"\x1aGetAttributeValuesResponse\x12,\n" +
	"\x06values\x18\x01 \x01(\v2\x14.api.AttributeValuesR\x06values2\xb9\x02\n" +
	"\fQueryService\x12[\n" +
	"\n" +
	"ExecuteSQL\x12\x16.api.ExecuteSQLRequest\x1a\x17.api.ExecuteSQLResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/sql/query\x12\\\n" +
	"\x0eGetPhotoSchema\x12\n" +
	".api.Empty\x1a\x1b.api.GetPhotoSchemaResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/sql/photos/schema\x12n\n" +
	"\x12GetAttributeValues\x12\n" +
	".api.Empty\x1a\x1f.api.GetAttributeValuesResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1/sql/photos/attribute-valuesB\"Z backend-new/internal/pkg/api;apib\x06proto3"

var (
	file_query_service_proto_rawDescOnce sync.Once
	file_query_service_proto_rawDescData []byte
)

func file_query_service_proto_rawDescGZIP() []byte {
	file_query_service_proto_rawDescOnce.Do(func() {
		file_query_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_service_proto_rawDesc), len(file_query_service_proto_rawDesc)))
	})
	return file_query_service_proto_rawDescData
}

var file_query_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_query_service_proto_goTypes = []any{
	(*ExecuteSQLRequest)(nil),          // 0: api.ExecuteSQLRequest
	(*ExecuteSQLResponse)(nil),         // 1: api.ExecuteSQLResponse
	(*SchemaField)(nil),                // 2: api.SchemaField
	(*GetPhotoSchemaResponse)(nil),     // 3: api.GetPhotoSchemaResponse
	(*AttributeValues)(nil),            // 4: api.AttributeValues
	(*GetAttributeValuesResponse)(nil), // 5: api.GetAttributeValuesResponse
	(*structpb.Struct)(nil),            // 6: google.protobuf.Struct
	(*Empty)(nil),                      // 7: api.Empty
}
var file_query_service_proto_depIdxs = []int32{
	6, // 0: api.ExecuteSQLResponse.rows:type_name -> google.protobuf.Struct
	2, // 1: api.GetPhotoSchemaResponse.fields:type_name -> api.SchemaField
	4, // 2: api.GetAttributeValuesResponse.values:type_name -> api.AttributeValues
	0, // 3: api.QueryService.ExecuteSQL:input_type -> api.ExecuteSQLRequest
	7, // 4: api.QueryService.GetPhotoSchema:input_type -> api.Empty
	7, // 5: api.QueryService.GetAttributeValues:input_type -> api.Empty
	1, // 6: api.QueryService.ExecuteSQL:output_type -> api.ExecuteSQLResponse
	3, // 7: api.QueryService.GetPhotoSchema:output_type -> api.GetPhotoSchemaResponse
	5, // 8: api.QueryService.GetAttributeValues:output_type -> api.GetAttributeValuesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_query_service_proto_init() }
func file_query_service_proto_init() {
	if File_query_service_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_service_proto_rawDesc), len(file_query_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_service_proto_goTypes,
		DependencyIndexes: file_query_service_proto_depIdxs,
		MessageInfos:      file_query_service_proto_msgTypes,
	}.Build()
	File_query_service_proto = out.File
	file_query_service_proto_goTypes = nil
	file_query_service_proto_depIdxs = nil
}
