// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: tag_service.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsResponse) Reset() {
	*x = ListTagsResponse{}
	mi := &file_tag_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResponse) ProtoMessage() {}

func (x *ListTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResponse.ProtoReflect.Descriptor instead.
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return file_tag_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListTagsResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetPhotosByTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPhotosByTagRequest) Reset() {
	*x = GetPhotosByTagRequest{}
	mi := &file_tag_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhotosByTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhotosByTagRequest) ProtoMessage() {}

func (x *GetPhotosByTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhotosByTagRequest.ProtoReflect.Descriptor instead.
func (*GetPhotosByTagRequest) Descriptor() ([]byte, []int) {
	return file_tag_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetPhotosByTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPhotosByTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Items         []*PhotoItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPhotosByTagResponse) Reset() {
	*x = GetPhotosByTagResponse{}
	mi := &file_tag_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhotosByTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhotosByTagResponse) ProtoMessage() {}

func (x *GetPhotosByTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhotosByTagResponse.ProtoReflect.Descriptor instead.
func (*GetPhotosByTagResponse) Descriptor() ([]byte, []int) {
	return file_tag_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetPhotosByTagResponse) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *GetPhotosByTagResponse) GetItems() []*PhotoItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetPhotosByTagResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BindTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhotoIds      []string               `protobuf:"bytes,1,rep,name=photo_ids,json=photoIds,proto3" json:"photo_ids,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindTagsRequest) Reset() {
	*x = BindTagsRequest{}
	mi := &file_tag_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindTagsRequest) ProtoMessage() {}

func (x *BindTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindTagsRequest.ProtoReflect.Descriptor instead.
func (*BindTagsRequest) Descriptor() ([]byte, []int) {
	return file_tag_service_proto_rawDescGZIP(), []int{3}
}

func (x *BindTagsRequest) GetPhotoIds() []string {
	if x != nil {
		return x.PhotoIds
	}
	return nil
}

func (x *BindTagsRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type BindTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindTagsResponse) Reset() {
	*x = BindTagsResponse{}
	mi := &file_tag_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindTagsResponse) ProtoMessage() {}

func (x *BindTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindTagsResponse.ProtoReflect.Descriptor instead.
func (*BindTagsResponse) Descriptor() ([]byte, []int) {
	return file_tag_service_proto_rawDescGZIP(), []int{4}
}

func (x *BindTagsResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BindTagsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnbindTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhotoIds      []string               `protobuf:"bytes,1,rep,name=photo_ids,json=photoIds,proto3" json:"photo_ids,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindTagsRequest) Reset() {
	*x = UnbindTagsRequest{}
	mi := &file_tag_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindTagsRequest) ProtoMessage() {}

func (x *UnbindTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindTagsRequest.ProtoReflect.Descriptor instead.
func (*UnbindTagsRequest) Descriptor() ([]byte, []int) {
	return file_tag_service_proto_rawDescGZIP(), []int{5}
}

func (x *UnbindTagsRequest) GetPhotoIds() []string {
	if x != nil {
		return x.PhotoIds
	}
	return nil
}

func (x *UnbindTagsRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type UnbindTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindTagsResponse) Reset() {
	*x = UnbindTagsResponse{}
	mi := &file_tag_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindTagsResponse) ProtoMessage() {}

func (x *UnbindTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindTagsResponse.ProtoReflect.Descriptor instead.
func (*UnbindTagsResponse) Descriptor() ([]byte, []int) {
	return file_tag_service_proto_rawDescGZIP(), []int{6}
}

func (x *UnbindTagsResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *UnbindTagsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_tag_service_proto protoreflect.FileDescriptor

const file_tag_service_proto_rawDesc = "" +
	"\n" +
	"\x11tag_service.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\fcommon.proto\x1a\x13photo_service.proto\"&\n" +
	"\x10ListTagsResponse\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\"+\n" +
	"\x15GetPhotosByTagRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"f\n" +
	"\x16GetPhotosByTagResponse\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12$\n" +
	"\x05items\x18\x02 \x03(\v2\x0e.api.PhotoItemR\x05items\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"@\n" +
	"\x0fBindTagsRequest\x12\x1b\n" +
	"\tphoto_ids\x18\x01 \x03(\tR\bphotoIds\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\"Q\n" +
	"\x10BindTagsResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\x11UnbindTagsRequest\x12\x1b\n" +
	"\tphoto_ids\x18\x01 \x03(\tR\bphotoIds\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\"S\n" +
	"\x12UnbindTagsResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf6\x02\n" +
	"\n" +
	"TagService\x12C\n" +
	"\bListTags\x12\n" +
	".api.Empty\x1a\x15.api.ListTagsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/tags\x12m\n" +
	"\x0eGetPhotosByTag\x12\x1a.api.GetPhotosByTagRequest\x1a\x1b.api.GetPhotosByTagResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/tags/{name}/photos\x12U\n" +
	"\bBindTags\x12\x14.api.BindTagsRequest\x1a\x15.api.BindTagsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/tags/bind\x12]\n" +
	"\n" +
	"UnbindTags\x12\x16.api.UnbindTagsRequest\x1a\x17.api.UnbindTagsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/tags/unbindB\"Z backend-new/internal/pkg/api;apib\x06proto3"

var (
	file_tag_service_proto_rawDescOnce sync.Once
	file_tag_service_proto_rawDescData []byte
)

func file_tag_service_proto_rawDescGZIP() []byte {
	file_tag_service_proto_rawDescOnce.Do(func() {
		file_tag_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tag_service_proto_rawDesc), len(file_tag_service_proto_rawDesc)))
	})
	return file_tag_service_proto_rawDescData
}

var file_tag_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tag_service_proto_goTypes = []any{
	(*ListTagsResponse)(nil),       // 0: api.ListTagsResponse
	(*GetPhotosByTagRequest)(nil),  // 1: api.GetPhotosByTagRequest
	(*GetPhotosByTagResponse)(nil), // 2: api.GetPhotosByTagResponse
	(*BindTagsRequest)(nil),        // 3: api.BindTagsRequest
	(*BindTagsResponse)(nil),       // 4: api.BindTagsResponse
	(*UnbindTagsRequest)(nil),      // 5: api.UnbindTagsRequest
	(*UnbindTagsResponse)(nil),     // 6: api.UnbindTagsResponse
	(*PhotoItem)(nil),              // 7: api.PhotoItem
	(*Empty)(nil),                  // 8: api.Empty
}
var file_tag_service_proto_depIdxs = []int32{
	7, // 0: api.GetPhotosByTagResponse.items:type_name -> api.PhotoItem
	8, // 1: api.TagService.ListTags:input_type -> api.Empty
	1, // 2: api.TagService.GetPhotosByTag:input_type -> api.GetPhotosByTagRequest
	3, // 3: api.TagService.BindTags:input_type -> api.BindTagsRequest
	5, // 4: api.TagService.UnbindTags:input_type -> api.UnbindTagsRequest
	0, // 5: api.TagService.ListTags:output_type -> api.ListTagsResponse
	2, // 6: api.TagService.GetPhotosByTag:output_type -> api.GetPhotosByTagResponse
	4, // 7: api.TagService.BindTags:output_type -> api.BindTagsResponse
	6, // 8: api.TagService.UnbindTags:output_type -> api.UnbindTagsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tag_service_proto_init() }
func file_tag_service_proto_init() {
	if File_tag_service_proto != nil {
		return
	}
	file_common_proto_init()
	file_photo_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tag_service_proto_rawDesc), len(file_tag_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tag_service_proto_goTypes,
		DependencyIndexes: file_tag_service_proto_depIdxs,
		MessageInfos:      file_tag_service_proto_msgTypes,
	}.Build()
	File_tag_service_proto = out.File
	file_tag_service_proto_goTypes = nil
	file_tag_service_proto_depIdxs = nil
}
