// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: vlm_service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VlmService_StartVlmQueue_FullMethodName     = "/api.VlmService/StartVlmQueue"
	VlmService_StopVlmQueue_FullMethodName      = "/api.VlmService/StopVlmQueue"
	VlmService_GetVlmQueueStatus_FullMethodName = "/api.VlmService/GetVlmQueueStatus"
	VlmService_DescribePhoto_FullMethodName     = "/api.VlmService/DescribePhoto"
)

// VlmServiceClient is the client API for VlmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VlmService VLM 队列控制 + 单张照片 VLM 描述
type VlmServiceClient interface {
	// 启动 VLM 队列处理
	StartVlmQueue(ctx context.Context, in *StartVlmQueueRequest, opts ...grpc.CallOption) (*StartVlmQueueResponse, error)
	// 中止 VLM 队列处理
	StopVlmQueue(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StopVlmQueueResponse, error)
	// 查询 VLM 队列状态
	GetVlmQueueStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetVlmQueueStatusResponse, error)
	// 单张照片触发 VLM 描述
	DescribePhoto(ctx context.Context, in *DescribePhotoRequest, opts ...grpc.CallOption) (*DescribePhotoResponse, error)
}

type vlmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVlmServiceClient(cc grpc.ClientConnInterface) VlmServiceClient {
	return &vlmServiceClient{cc}
}

func (c *vlmServiceClient) StartVlmQueue(ctx context.Context, in *StartVlmQueueRequest, opts ...grpc.CallOption) (*StartVlmQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartVlmQueueResponse)
	err := c.cc.Invoke(ctx, VlmService_StartVlmQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vlmServiceClient) StopVlmQueue(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StopVlmQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopVlmQueueResponse)
	err := c.cc.Invoke(ctx, VlmService_StopVlmQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vlmServiceClient) GetVlmQueueStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetVlmQueueStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVlmQueueStatusResponse)
	err := c.cc.Invoke(ctx, VlmService_GetVlmQueueStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vlmServiceClient) DescribePhoto(ctx context.Context, in *DescribePhotoRequest, opts ...grpc.CallOption) (*DescribePhotoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribePhotoResponse)
	err := c.cc.Invoke(ctx, VlmService_DescribePhoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VlmServiceServer is the server API for VlmService service.
// All implementations must embed UnimplementedVlmServiceServer
// for forward compatibility.
//
// VlmService VLM 队列控制 + 单张照片 VLM 描述
type VlmServiceServer interface {
	// 启动 VLM 队列处理
	StartVlmQueue(context.Context, *StartVlmQueueRequest) (*StartVlmQueueResponse, error)
	// 中止 VLM 队列处理
	StopVlmQueue(context.Context, *Empty) (*StopVlmQueueResponse, error)
	// 查询 VLM 队列状态
	GetVlmQueueStatus(context.Context, *Empty) (*GetVlmQueueStatusResponse, error)
	// 单张照片触发 VLM 描述
	DescribePhoto(context.Context, *DescribePhotoRequest) (*DescribePhotoResponse, error)
	mustEmbedUnimplementedVlmServiceServer()
}

// UnimplementedVlmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVlmServiceServer struct{}

func (UnimplementedVlmServiceServer) StartVlmQueue(context.Context, *StartVlmQueueRequest) (*StartVlmQueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVlmQueue not implemented")
}
func (UnimplementedVlmServiceServer) StopVlmQueue(context.Context, *Empty) (*StopVlmQueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopVlmQueue not implemented")
}
func (UnimplementedVlmServiceServer) GetVlmQueueStatus(context.Context, *Empty) (*GetVlmQueueStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVlmQueueStatus not implemented")
}
func (UnimplementedVlmServiceServer) DescribePhoto(context.Context, *DescribePhotoRequest) (*DescribePhotoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribePhoto not implemented")
}
func (UnimplementedVlmServiceServer) mustEmbedUnimplementedVlmServiceServer() {}
func (UnimplementedVlmServiceServer) testEmbeddedByValue()                    {}

// UnsafeVlmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VlmServiceServer will
// result in compilation errors.
type UnsafeVlmServiceServer interface {
	mustEmbedUnimplementedVlmServiceServer()
}

func RegisterVlmServiceServer(s grpc.ServiceRegistrar, srv VlmServiceServer) {
	// If the following call panics, it indicates UnimplementedVlmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VlmService_ServiceDesc, srv)
}

func _VlmService_StartVlmQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVlmQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VlmServiceServer).StartVlmQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VlmService_StartVlmQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VlmServiceServer).StartVlmQueue(ctx, req.(*StartVlmQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VlmService_StopVlmQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VlmServiceServer).StopVlmQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VlmService_StopVlmQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VlmServiceServer).StopVlmQueue(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VlmService_GetVlmQueueStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VlmServiceServer).GetVlmQueueStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VlmService_GetVlmQueueStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VlmServiceServer).GetVlmQueueStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VlmService_DescribePhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribePhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VlmServiceServer).DescribePhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VlmService_DescribePhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VlmServiceServer).DescribePhoto(ctx, req.(*DescribePhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VlmService_ServiceDesc is the grpc.ServiceDesc for VlmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VlmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.VlmService",
	HandlerType: (*VlmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartVlmQueue",
			Handler:    _VlmService_StartVlmQueue_Handler,
		},
		{
			MethodName: "StopVlmQueue",
			Handler:    _VlmService_StopVlmQueue_Handler,
		},
		{
			MethodName: "GetVlmQueueStatus",
			Handler:    _VlmService_GetVlmQueueStatus_Handler,
		},
		{
			MethodName: "DescribePhoto",
			Handler:    _VlmService_DescribePhoto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vlm_service.proto",
}
