// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: timeline_service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TimelineService_ListTimelines_FullMethodName       = "/api.TimelineService/ListTimelines"
	TimelineService_GetPhotosByTimeline_FullMethodName = "/api.TimelineService/GetPhotosByTimeline"
)

// TimelineServiceClient is the client API for TimelineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TimelineService 时间线服务
type TimelineServiceClient interface {
	// 所有时间线列表
	ListTimelines(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListTimelinesResponse, error)
	// 某时间线下的照片
	GetPhotosByTimeline(ctx context.Context, in *GetPhotosByTimelineRequest, opts ...grpc.CallOption) (*GetPhotosByTimelineResponse, error)
}

type timelineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimelineServiceClient(cc grpc.ClientConnInterface) TimelineServiceClient {
	return &timelineServiceClient{cc}
}

func (c *timelineServiceClient) ListTimelines(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListTimelinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTimelinesResponse)
	err := c.cc.Invoke(ctx, TimelineService_ListTimelines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timelineServiceClient) GetPhotosByTimeline(ctx context.Context, in *GetPhotosByTimelineRequest, opts ...grpc.CallOption) (*GetPhotosByTimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPhotosByTimelineResponse)
	err := c.cc.Invoke(ctx, TimelineService_GetPhotosByTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimelineServiceServer is the server API for TimelineService service.
// All implementations must embed UnimplementedTimelineServiceServer
// for forward compatibility.
//
// TimelineService 时间线服务
type TimelineServiceServer interface {
	// 所有时间线列表
	ListTimelines(context.Context, *Empty) (*ListTimelinesResponse, error)
	// 某时间线下的照片
	GetPhotosByTimeline(context.Context, *GetPhotosByTimelineRequest) (*GetPhotosByTimelineResponse, error)
	mustEmbedUnimplementedTimelineServiceServer()
}

// UnimplementedTimelineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimelineServiceServer struct{}

func (UnimplementedTimelineServiceServer) ListTimelines(context.Context, *Empty) (*ListTimelinesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTimelines not implemented")
}
func (UnimplementedTimelineServiceServer) GetPhotosByTimeline(context.Context, *GetPhotosByTimelineRequest) (*GetPhotosByTimelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPhotosByTimeline not implemented")
}
func (UnimplementedTimelineServiceServer) mustEmbedUnimplementedTimelineServiceServer() {}
func (UnimplementedTimelineServiceServer) testEmbeddedByValue()                         {}

// UnsafeTimelineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimelineServiceServer will
// result in compilation errors.
type UnsafeTimelineServiceServer interface {
	mustEmbedUnimplementedTimelineServiceServer()
}

func RegisterTimelineServiceServer(s grpc.ServiceRegistrar, srv TimelineServiceServer) {
	// If the following call panics, it indicates UnimplementedTimelineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TimelineService_ServiceDesc, srv)
}

func _TimelineService_ListTimelines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimelineServiceServer).ListTimelines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimelineService_ListTimelines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimelineServiceServer).ListTimelines(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimelineService_GetPhotosByTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhotosByTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimelineServiceServer).GetPhotosByTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimelineService_GetPhotosByTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimelineServiceServer).GetPhotosByTimeline(ctx, req.(*GetPhotosByTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TimelineService_ServiceDesc is the grpc.ServiceDesc for TimelineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimelineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.TimelineService",
	HandlerType: (*TimelineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTimelines",
			Handler:    _TimelineService_ListTimelines_Handler,
		},
		{
			MethodName: "GetPhotosByTimeline",
			Handler:    _TimelineService_GetPhotosByTimeline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "timeline_service.proto",
}
