// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: vlm_service.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartVlmQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVlmQueueRequest) Reset() {
	*x = StartVlmQueueRequest{}
	mi := &file_vlm_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVlmQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVlmQueueRequest) ProtoMessage() {}

func (x *StartVlmQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vlm_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVlmQueueRequest.ProtoReflect.Descriptor instead.
func (*StartVlmQueueRequest) Descriptor() ([]byte, []int) {
	return file_vlm_service_proto_rawDescGZIP(), []int{0}
}

func (x *StartVlmQueueRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type StartVlmQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVlmQueueResponse) Reset() {
	*x = StartVlmQueueResponse{}
	mi := &file_vlm_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVlmQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVlmQueueResponse) ProtoMessage() {}

func (x *StartVlmQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vlm_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVlmQueueResponse.ProtoReflect.Descriptor instead.
func (*StartVlmQueueResponse) Descriptor() ([]byte, []int) {
	return file_vlm_service_proto_rawDescGZIP(), []int{1}
}

func (x *StartVlmQueueResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StartVlmQueueResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *StartVlmQueueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopVlmQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stopped       bool                   `protobuf:"varint,1,opt,name=stopped,proto3" json:"stopped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVlmQueueResponse) Reset() {
	*x = StopVlmQueueResponse{}
	mi := &file_vlm_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVlmQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVlmQueueResponse) ProtoMessage() {}

func (x *StopVlmQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vlm_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVlmQueueResponse.ProtoReflect.Descriptor instead.
func (*StopVlmQueueResponse) Descriptor() ([]byte, []int) {
	return file_vlm_service_proto_rawDescGZIP(), []int{2}
}

func (x *StopVlmQueueResponse) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

type VlmQueueStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Completed     int32                  `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	Failed        int32                  `protobuf:"varint,4,opt,name=failed,proto3" json:"failed,omitempty"`
	CurrentFile   string                 `protobuf:"bytes,5,opt,name=current_file,json=currentFile,proto3" json:"current_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VlmQueueStatus) Reset() {
	*x = VlmQueueStatus{}
	mi := &file_vlm_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlmQueueStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlmQueueStatus) ProtoMessage() {}

func (x *VlmQueueStatus) ProtoReflect() protoreflect.Message {
	mi := &file_vlm_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlmQueueStatus.ProtoReflect.Descriptor instead.
func (*VlmQueueStatus) Descriptor() ([]byte, []int) {
	return file_vlm_service_proto_rawDescGZIP(), []int{3}
}

func (x *VlmQueueStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *VlmQueueStatus) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *VlmQueueStatus) GetCompleted() int32 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *VlmQueueStatus) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *VlmQueueStatus) GetCurrentFile() string {
	if x != nil {
		return x.CurrentFile
	}
	return ""
}

type GetVlmQueueStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *VlmQueueStatus        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVlmQueueStatusResponse) Reset() {
	*x = GetVlmQueueStatusResponse{}
	mi := &file_vlm_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVlmQueueStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVlmQueueStatusResponse) ProtoMessage() {}

func (x *GetVlmQueueStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vlm_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVlmQueueStatusResponse.ProtoReflect.Descriptor instead.
func (*GetVlmQueueStatusResponse) Descriptor() ([]byte, []int) {
	return file_vlm_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetVlmQueueStatusResponse) GetStatus() *VlmQueueStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type DescribePhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribePhotoRequest) Reset() {
	*x = DescribePhotoRequest{}
	mi := &file_vlm_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribePhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribePhotoRequest) ProtoMessage() {}

func (x *DescribePhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vlm_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribePhotoRequest.ProtoReflect.Descriptor instead.
func (*DescribePhotoRequest) Descriptor() ([]byte, []int) {
	return file_vlm_service_proto_rawDescGZIP(), []int{5}
}

func (x *DescribePhotoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DescribePhotoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queued        bool                   `protobuf:"varint,1,opt,name=queued,proto3" json:"queued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribePhotoResponse) Reset() {
	*x = DescribePhotoResponse{}
	mi := &file_vlm_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribePhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribePhotoResponse) ProtoMessage() {}

func (x *DescribePhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vlm_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribePhotoResponse.ProtoReflect.Descriptor instead.
func (*DescribePhotoResponse) Descriptor() ([]byte, []int) {
	return file_vlm_service_proto_rawDescGZIP(), []int{6}
}

func (x *DescribePhotoResponse) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

var File_vlm_service_proto protoreflect.FileDescriptor

const file_vlm_service_proto_rawDesc = "" +
	"\n" +
	"\x11vlm_service.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\fcommon.proto\",\n" +
	"\x14StartVlmQueueRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"`\n" +
	"\x15StartVlmQueueResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"0\n" +
	"\x14StopVlmQueueResponse\x12\x18\n" +
	"\astopped\x18\x01 \x01(\bR\astopped\"\x99\x01\n" +
	"\x0eVlmQueueStatus\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\x05R\tcompleted\x12\x16\n" +
	"\x06failed\x18\x04 \x01(\x05R\x06failed\x12!\n" +
	"\fcurrent_file\x18\x05 \x01(\tR\vcurrentFile\"H\n" +
	"\x19GetVlmQueueStatusResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.api.VlmQueueStatusR\x06status\"&\n" +
	"\x14DescribePhotoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x15DescribePhotoResponse\x12\x16\n" +
	"\x06queued\x18\x01 \x01(\bR\x06queued2\xa6\x03\n" +
	"\n" +
	"VlmService\x12j\n" +
	"\rStartVlmQueue\x12\x19.api.StartVlmQueueRequest\x1a\x1a.api.StartVlmQueueResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/vlm/queue/start\x12X\n" +
	"\fStopVlmQueue\x12\n" +
	".api.Empty\x1a\x19.api.StopVlmQueueResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/vlm/queue/stop\x12a\n" +
	"\x11GetVlmQueueStatus\x12\n" +
	".api.Empty\x1a\x1e.api.GetVlmQueueStatusResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/vlm/queue/status\x12o\n" +
	"\rDescribePhoto\x12\x19.api.DescribePhotoRequest\x1a\x1a.api.DescribePhotoResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/photos/{id}/describeB\x1eZ\x1cbackend/internal/pkg/api;apib\x06proto3"

var (
	file_vlm_service_proto_rawDescOnce sync.Once
	file_vlm_service_proto_rawDescData []byte
)

func file_vlm_service_proto_rawDescGZIP() []byte {
	file_vlm_service_proto_rawDescOnce.Do(func() {
		file_vlm_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vlm_service_proto_rawDesc), len(file_vlm_service_proto_rawDesc)))
	})
	return file_vlm_service_proto_rawDescData
}

var file_vlm_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_vlm_service_proto_goTypes = []any{
	(*StartVlmQueueRequest)(nil),      // 0: api.StartVlmQueueRequest
	(*StartVlmQueueResponse)(nil),     // 1: api.StartVlmQueueResponse
	(*StopVlmQueueResponse)(nil),      // 2: api.StopVlmQueueResponse
	(*VlmQueueStatus)(nil),            // 3: api.VlmQueueStatus
	(*GetVlmQueueStatusResponse)(nil), // 4: api.GetVlmQueueStatusResponse
	(*DescribePhotoRequest)(nil),      // 5: api.DescribePhotoRequest
	(*DescribePhotoResponse)(nil),     // 6: api.DescribePhotoResponse
	(*Empty)(nil),                     // 7: api.Empty
}
var file_vlm_service_proto_depIdxs = []int32{
	3, // 0: api.GetVlmQueueStatusResponse.status:type_name -> api.VlmQueueStatus
	0, // 1: api.VlmService.StartVlmQueue:input_type -> api.StartVlmQueueRequest
	7, // 2: api.VlmService.StopVlmQueue:input_type -> api.Empty
	7, // 3: api.VlmService.GetVlmQueueStatus:input_type -> api.Empty
	5, // 4: api.VlmService.DescribePhoto:input_type -> api.DescribePhotoRequest
	1, // 5: api.VlmService.StartVlmQueue:output_type -> api.StartVlmQueueResponse
	2, // 6: api.VlmService.StopVlmQueue:output_type -> api.StopVlmQueueResponse
	4, // 7: api.VlmService.GetVlmQueueStatus:output_type -> api.GetVlmQueueStatusResponse
	6, // 8: api.VlmService.DescribePhoto:output_type -> api.DescribePhotoResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vlm_service_proto_init() }
func file_vlm_service_proto_init() {
	if File_vlm_service_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vlm_service_proto_rawDesc), len(file_vlm_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vlm_service_proto_goTypes,
		DependencyIndexes: file_vlm_service_proto_depIdxs,
		MessageInfos:      file_vlm_service_proto_msgTypes,
	}.Build()
	File_vlm_service_proto = out.File
	file_vlm_service_proto_goTypes = nil
	file_vlm_service_proto_depIdxs = nil
}
