// Code generated by tools/genCURD. DO NOT EDIT.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: z_defaultService.gen.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DefaultCURD_AddPhotoGroup_FullMethodName         = "/api.defaultCURD/AddPhotoGroup"
	DefaultCURD_GetPhotoGroupList_FullMethodName     = "/api.defaultCURD/GetPhotoGroupList"
	DefaultCURD_UpdatePhotoGroup_FullMethodName      = "/api.defaultCURD/UpdatePhotoGroup"
	DefaultCURD_DelPhotoGroupByIDList_FullMethodName = "/api.defaultCURD/DelPhotoGroupByIDList"
	DefaultCURD_AddPhoto_FullMethodName              = "/api.defaultCURD/AddPhoto"
	DefaultCURD_GetPhotoList_FullMethodName          = "/api.defaultCURD/GetPhotoList"
	DefaultCURD_UpdatePhoto_FullMethodName           = "/api.defaultCURD/UpdatePhoto"
	DefaultCURD_DelPhotoByIDList_FullMethodName      = "/api.defaultCURD/DelPhotoByIDList"
)

// DefaultCURDClient is the client API for DefaultCURD service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --------------------------------------------------
type DefaultCURDClient interface {
	// --------------------------------------------------
	// tbl : photo_groups
	AddPhotoGroup(ctx context.Context, in *AddPhotoGroupRequest, opts ...grpc.CallOption) (*AddPhotoGroupResponse, error)
	GetPhotoGroupList(ctx context.Context, in *GetPhotoGroupListRequest, opts ...grpc.CallOption) (*GetPhotoGroupListResponse, error)
	UpdatePhotoGroup(ctx context.Context, in *UpdatePhotoGroupRequest, opts ...grpc.CallOption) (*UpdatePhotoGroupResponse, error)
	DelPhotoGroupByIDList(ctx context.Context, in *DelPhotoGroupByIDListRequest, opts ...grpc.CallOption) (*Empty, error)
	// --------------------------------------------------
	// tbl : photos
	AddPhoto(ctx context.Context, in *AddPhotoRequest, opts ...grpc.CallOption) (*AddPhotoResponse, error)
	GetPhotoList(ctx context.Context, in *GetPhotoListRequest, opts ...grpc.CallOption) (*GetPhotoListResponse, error)
	UpdatePhoto(ctx context.Context, in *UpdatePhotoRequest, opts ...grpc.CallOption) (*UpdatePhotoResponse, error)
	DelPhotoByIDList(ctx context.Context, in *DelPhotoByIDListRequest, opts ...grpc.CallOption) (*Empty, error)
}

type defaultCURDClient struct {
	cc grpc.ClientConnInterface
}

func NewDefaultCURDClient(cc grpc.ClientConnInterface) DefaultCURDClient {
	return &defaultCURDClient{cc}
}

func (c *defaultCURDClient) AddPhotoGroup(ctx context.Context, in *AddPhotoGroupRequest, opts ...grpc.CallOption) (*AddPhotoGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPhotoGroupResponse)
	err := c.cc.Invoke(ctx, DefaultCURD_AddPhotoGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) GetPhotoGroupList(ctx context.Context, in *GetPhotoGroupListRequest, opts ...grpc.CallOption) (*GetPhotoGroupListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPhotoGroupListResponse)
	err := c.cc.Invoke(ctx, DefaultCURD_GetPhotoGroupList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) UpdatePhotoGroup(ctx context.Context, in *UpdatePhotoGroupRequest, opts ...grpc.CallOption) (*UpdatePhotoGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePhotoGroupResponse)
	err := c.cc.Invoke(ctx, DefaultCURD_UpdatePhotoGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) DelPhotoGroupByIDList(ctx context.Context, in *DelPhotoGroupByIDListRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DefaultCURD_DelPhotoGroupByIDList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) AddPhoto(ctx context.Context, in *AddPhotoRequest, opts ...grpc.CallOption) (*AddPhotoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPhotoResponse)
	err := c.cc.Invoke(ctx, DefaultCURD_AddPhoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) GetPhotoList(ctx context.Context, in *GetPhotoListRequest, opts ...grpc.CallOption) (*GetPhotoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPhotoListResponse)
	err := c.cc.Invoke(ctx, DefaultCURD_GetPhotoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) UpdatePhoto(ctx context.Context, in *UpdatePhotoRequest, opts ...grpc.CallOption) (*UpdatePhotoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePhotoResponse)
	err := c.cc.Invoke(ctx, DefaultCURD_UpdatePhoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) DelPhotoByIDList(ctx context.Context, in *DelPhotoByIDListRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DefaultCURD_DelPhotoByIDList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DefaultCURDServer is the server API for DefaultCURD service.
// All implementations must embed UnimplementedDefaultCURDServer
// for forward compatibility.
//
// --------------------------------------------------
type DefaultCURDServer interface {
	// --------------------------------------------------
	// tbl : photo_groups
	AddPhotoGroup(context.Context, *AddPhotoGroupRequest) (*AddPhotoGroupResponse, error)
	GetPhotoGroupList(context.Context, *GetPhotoGroupListRequest) (*GetPhotoGroupListResponse, error)
	UpdatePhotoGroup(context.Context, *UpdatePhotoGroupRequest) (*UpdatePhotoGroupResponse, error)
	DelPhotoGroupByIDList(context.Context, *DelPhotoGroupByIDListRequest) (*Empty, error)
	// --------------------------------------------------
	// tbl : photos
	AddPhoto(context.Context, *AddPhotoRequest) (*AddPhotoResponse, error)
	GetPhotoList(context.Context, *GetPhotoListRequest) (*GetPhotoListResponse, error)
	UpdatePhoto(context.Context, *UpdatePhotoRequest) (*UpdatePhotoResponse, error)
	DelPhotoByIDList(context.Context, *DelPhotoByIDListRequest) (*Empty, error)
	mustEmbedUnimplementedDefaultCURDServer()
}

// UnimplementedDefaultCURDServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDefaultCURDServer struct{}

func (UnimplementedDefaultCURDServer) AddPhotoGroup(context.Context, *AddPhotoGroupRequest) (*AddPhotoGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPhotoGroup not implemented")
}
func (UnimplementedDefaultCURDServer) GetPhotoGroupList(context.Context, *GetPhotoGroupListRequest) (*GetPhotoGroupListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPhotoGroupList not implemented")
}
func (UnimplementedDefaultCURDServer) UpdatePhotoGroup(context.Context, *UpdatePhotoGroupRequest) (*UpdatePhotoGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePhotoGroup not implemented")
}
func (UnimplementedDefaultCURDServer) DelPhotoGroupByIDList(context.Context, *DelPhotoGroupByIDListRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelPhotoGroupByIDList not implemented")
}
func (UnimplementedDefaultCURDServer) AddPhoto(context.Context, *AddPhotoRequest) (*AddPhotoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPhoto not implemented")
}
func (UnimplementedDefaultCURDServer) GetPhotoList(context.Context, *GetPhotoListRequest) (*GetPhotoListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPhotoList not implemented")
}
func (UnimplementedDefaultCURDServer) UpdatePhoto(context.Context, *UpdatePhotoRequest) (*UpdatePhotoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePhoto not implemented")
}
func (UnimplementedDefaultCURDServer) DelPhotoByIDList(context.Context, *DelPhotoByIDListRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelPhotoByIDList not implemented")
}
func (UnimplementedDefaultCURDServer) mustEmbedUnimplementedDefaultCURDServer() {}
func (UnimplementedDefaultCURDServer) testEmbeddedByValue()                     {}

// UnsafeDefaultCURDServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DefaultCURDServer will
// result in compilation errors.
type UnsafeDefaultCURDServer interface {
	mustEmbedUnimplementedDefaultCURDServer()
}

func RegisterDefaultCURDServer(s grpc.ServiceRegistrar, srv DefaultCURDServer) {
	// If the following call panics, it indicates UnimplementedDefaultCURDServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DefaultCURD_ServiceDesc, srv)
}

func _DefaultCURD_AddPhotoGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPhotoGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).AddPhotoGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_AddPhotoGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).AddPhotoGroup(ctx, req.(*AddPhotoGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_GetPhotoGroupList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhotoGroupListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).GetPhotoGroupList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_GetPhotoGroupList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).GetPhotoGroupList(ctx, req.(*GetPhotoGroupListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_UpdatePhotoGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePhotoGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).UpdatePhotoGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_UpdatePhotoGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).UpdatePhotoGroup(ctx, req.(*UpdatePhotoGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_DelPhotoGroupByIDList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelPhotoGroupByIDListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).DelPhotoGroupByIDList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_DelPhotoGroupByIDList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).DelPhotoGroupByIDList(ctx, req.(*DelPhotoGroupByIDListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_AddPhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).AddPhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_AddPhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).AddPhoto(ctx, req.(*AddPhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_GetPhotoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhotoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).GetPhotoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_GetPhotoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).GetPhotoList(ctx, req.(*GetPhotoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_UpdatePhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).UpdatePhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_UpdatePhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).UpdatePhoto(ctx, req.(*UpdatePhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_DelPhotoByIDList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelPhotoByIDListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).DelPhotoByIDList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_DelPhotoByIDList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).DelPhotoByIDList(ctx, req.(*DelPhotoByIDListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DefaultCURD_ServiceDesc is the grpc.ServiceDesc for DefaultCURD service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DefaultCURD_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.defaultCURD",
	HandlerType: (*DefaultCURDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPhotoGroup",
			Handler:    _DefaultCURD_AddPhotoGroup_Handler,
		},
		{
			MethodName: "GetPhotoGroupList",
			Handler:    _DefaultCURD_GetPhotoGroupList_Handler,
		},
		{
			MethodName: "UpdatePhotoGroup",
			Handler:    _DefaultCURD_UpdatePhotoGroup_Handler,
		},
		{
			MethodName: "DelPhotoGroupByIDList",
			Handler:    _DefaultCURD_DelPhotoGroupByIDList_Handler,
		},
		{
			MethodName: "AddPhoto",
			Handler:    _DefaultCURD_AddPhoto_Handler,
		},
		{
			MethodName: "GetPhotoList",
			Handler:    _DefaultCURD_GetPhotoList_Handler,
		},
		{
			MethodName: "UpdatePhoto",
			Handler:    _DefaultCURD_UpdatePhoto_Handler,
		},
		{
			MethodName: "DelPhotoByIDList",
			Handler:    _DefaultCURD_DelPhotoByIDList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "z_defaultService.gen.proto",
}
