// Code generated by tools/genCURD. DO NOT EDIT.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: z_defaultService.gen.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DefaultCURD_AddAppSetting_FullMethodName            = "/api.defaultCURD/AddAppSetting"
	DefaultCURD_GetAppSettingList_FullMethodName        = "/api.defaultCURD/GetAppSettingList"
	DefaultCURD_UpdateAppSetting_FullMethodName         = "/api.defaultCURD/UpdateAppSetting"
	DefaultCURD_DelAppSettingByKeyList_FullMethodName   = "/api.defaultCURD/DelAppSettingByKeyList"
	DefaultCURD_AddPhotoGroup_FullMethodName            = "/api.defaultCURD/AddPhotoGroup"
	DefaultCURD_GetPhotoGroupList_FullMethodName        = "/api.defaultCURD/GetPhotoGroupList"
	DefaultCURD_UpdatePhotoGroup_FullMethodName         = "/api.defaultCURD/UpdatePhotoGroup"
	DefaultCURD_DelPhotoGroupByIDList_FullMethodName    = "/api.defaultCURD/DelPhotoGroupByIDList"
	DefaultCURD_AddPhoto_FullMethodName                 = "/api.defaultCURD/AddPhoto"
	DefaultCURD_GetPhotoList_FullMethodName             = "/api.defaultCURD/GetPhotoList"
	DefaultCURD_UpdatePhoto_FullMethodName              = "/api.defaultCURD/UpdatePhoto"
	DefaultCURD_DelPhotoByIDList_FullMethodName         = "/api.defaultCURD/DelPhotoByIDList"
	DefaultCURD_AddTimelineEvent_FullMethodName         = "/api.defaultCURD/AddTimelineEvent"
	DefaultCURD_GetTimelineEventList_FullMethodName     = "/api.defaultCURD/GetTimelineEventList"
	DefaultCURD_UpdateTimelineEvent_FullMethodName      = "/api.defaultCURD/UpdateTimelineEvent"
	DefaultCURD_DelTimelineEventByIDList_FullMethodName = "/api.defaultCURD/DelTimelineEventByIDList"
)

// DefaultCURDClient is the client API for DefaultCURD service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --------------------------------------------------
type DefaultCURDClient interface {
	// --------------------------------------------------
	// tbl : app_settings
	AddAppSetting(ctx context.Context, in *AddAppSettingRequest, opts ...grpc.CallOption) (*AddAppSettingResponse, error)
	GetAppSettingList(ctx context.Context, in *GetAppSettingListRequest, opts ...grpc.CallOption) (*GetAppSettingListResponse, error)
	UpdateAppSetting(ctx context.Context, in *UpdateAppSettingRequest, opts ...grpc.CallOption) (*UpdateAppSettingResponse, error)
	DelAppSettingByKeyList(ctx context.Context, in *DelAppSettingByKeyListRequest, opts ...grpc.CallOption) (*Empty, error)
	// --------------------------------------------------
	// tbl : photo_groups
	AddPhotoGroup(ctx context.Context, in *AddPhotoGroupRequest, opts ...grpc.CallOption) (*AddPhotoGroupResponse, error)
	GetPhotoGroupList(ctx context.Context, in *GetPhotoGroupListRequest, opts ...grpc.CallOption) (*GetPhotoGroupListResponse, error)
	UpdatePhotoGroup(ctx context.Context, in *UpdatePhotoGroupRequest, opts ...grpc.CallOption) (*UpdatePhotoGroupResponse, error)
	DelPhotoGroupByIDList(ctx context.Context, in *DelPhotoGroupByIDListRequest, opts ...grpc.CallOption) (*Empty, error)
	// --------------------------------------------------
	// tbl : photos
	AddPhoto(ctx context.Context, in *AddPhotoRequest, opts ...grpc.CallOption) (*AddPhotoResponse, error)
	GetPhotoList(ctx context.Context, in *GetPhotoListRequest, opts ...grpc.CallOption) (*GetPhotoListResponse, error)
	UpdatePhoto(ctx context.Context, in *UpdatePhotoRequest, opts ...grpc.CallOption) (*UpdatePhotoResponse, error)
	DelPhotoByIDList(ctx context.Context, in *DelPhotoByIDListRequest, opts ...grpc.CallOption) (*Empty, error)
	// --------------------------------------------------
	// tbl : timeline_events
	AddTimelineEvent(ctx context.Context, in *AddTimelineEventRequest, opts ...grpc.CallOption) (*AddTimelineEventResponse, error)
	GetTimelineEventList(ctx context.Context, in *GetTimelineEventListRequest, opts ...grpc.CallOption) (*GetTimelineEventListResponse, error)
	UpdateTimelineEvent(ctx context.Context, in *UpdateTimelineEventRequest, opts ...grpc.CallOption) (*UpdateTimelineEventResponse, error)
	DelTimelineEventByIDList(ctx context.Context, in *DelTimelineEventByIDListRequest, opts ...grpc.CallOption) (*Empty, error)
}

type defaultCURDClient struct {
	cc grpc.ClientConnInterface
}

func NewDefaultCURDClient(cc grpc.ClientConnInterface) DefaultCURDClient {
	return &defaultCURDClient{cc}
}

func (c *defaultCURDClient) AddAppSetting(ctx context.Context, in *AddAppSettingRequest, opts ...grpc.CallOption) (*AddAppSettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAppSettingResponse)
	err := c.cc.Invoke(ctx, DefaultCURD_AddAppSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) GetAppSettingList(ctx context.Context, in *GetAppSettingListRequest, opts ...grpc.CallOption) (*GetAppSettingListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppSettingListResponse)
	err := c.cc.Invoke(ctx, DefaultCURD_GetAppSettingList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) UpdateAppSetting(ctx context.Context, in *UpdateAppSettingRequest, opts ...grpc.CallOption) (*UpdateAppSettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAppSettingResponse)
	err := c.cc.Invoke(ctx, DefaultCURD_UpdateAppSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) DelAppSettingByKeyList(ctx context.Context, in *DelAppSettingByKeyListRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DefaultCURD_DelAppSettingByKeyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) AddPhotoGroup(ctx context.Context, in *AddPhotoGroupRequest, opts ...grpc.CallOption) (*AddPhotoGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPhotoGroupResponse)
	err := c.cc.Invoke(ctx, DefaultCURD_AddPhotoGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) GetPhotoGroupList(ctx context.Context, in *GetPhotoGroupListRequest, opts ...grpc.CallOption) (*GetPhotoGroupListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPhotoGroupListResponse)
	err := c.cc.Invoke(ctx, DefaultCURD_GetPhotoGroupList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) UpdatePhotoGroup(ctx context.Context, in *UpdatePhotoGroupRequest, opts ...grpc.CallOption) (*UpdatePhotoGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePhotoGroupResponse)
	err := c.cc.Invoke(ctx, DefaultCURD_UpdatePhotoGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) DelPhotoGroupByIDList(ctx context.Context, in *DelPhotoGroupByIDListRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DefaultCURD_DelPhotoGroupByIDList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) AddPhoto(ctx context.Context, in *AddPhotoRequest, opts ...grpc.CallOption) (*AddPhotoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPhotoResponse)
	err := c.cc.Invoke(ctx, DefaultCURD_AddPhoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) GetPhotoList(ctx context.Context, in *GetPhotoListRequest, opts ...grpc.CallOption) (*GetPhotoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPhotoListResponse)
	err := c.cc.Invoke(ctx, DefaultCURD_GetPhotoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) UpdatePhoto(ctx context.Context, in *UpdatePhotoRequest, opts ...grpc.CallOption) (*UpdatePhotoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePhotoResponse)
	err := c.cc.Invoke(ctx, DefaultCURD_UpdatePhoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) DelPhotoByIDList(ctx context.Context, in *DelPhotoByIDListRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DefaultCURD_DelPhotoByIDList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) AddTimelineEvent(ctx context.Context, in *AddTimelineEventRequest, opts ...grpc.CallOption) (*AddTimelineEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTimelineEventResponse)
	err := c.cc.Invoke(ctx, DefaultCURD_AddTimelineEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) GetTimelineEventList(ctx context.Context, in *GetTimelineEventListRequest, opts ...grpc.CallOption) (*GetTimelineEventListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTimelineEventListResponse)
	err := c.cc.Invoke(ctx, DefaultCURD_GetTimelineEventList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) UpdateTimelineEvent(ctx context.Context, in *UpdateTimelineEventRequest, opts ...grpc.CallOption) (*UpdateTimelineEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTimelineEventResponse)
	err := c.cc.Invoke(ctx, DefaultCURD_UpdateTimelineEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *defaultCURDClient) DelTimelineEventByIDList(ctx context.Context, in *DelTimelineEventByIDListRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DefaultCURD_DelTimelineEventByIDList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DefaultCURDServer is the server API for DefaultCURD service.
// All implementations must embed UnimplementedDefaultCURDServer
// for forward compatibility.
//
// --------------------------------------------------
type DefaultCURDServer interface {
	// --------------------------------------------------
	// tbl : app_settings
	AddAppSetting(context.Context, *AddAppSettingRequest) (*AddAppSettingResponse, error)
	GetAppSettingList(context.Context, *GetAppSettingListRequest) (*GetAppSettingListResponse, error)
	UpdateAppSetting(context.Context, *UpdateAppSettingRequest) (*UpdateAppSettingResponse, error)
	DelAppSettingByKeyList(context.Context, *DelAppSettingByKeyListRequest) (*Empty, error)
	// --------------------------------------------------
	// tbl : photo_groups
	AddPhotoGroup(context.Context, *AddPhotoGroupRequest) (*AddPhotoGroupResponse, error)
	GetPhotoGroupList(context.Context, *GetPhotoGroupListRequest) (*GetPhotoGroupListResponse, error)
	UpdatePhotoGroup(context.Context, *UpdatePhotoGroupRequest) (*UpdatePhotoGroupResponse, error)
	DelPhotoGroupByIDList(context.Context, *DelPhotoGroupByIDListRequest) (*Empty, error)
	// --------------------------------------------------
	// tbl : photos
	AddPhoto(context.Context, *AddPhotoRequest) (*AddPhotoResponse, error)
	GetPhotoList(context.Context, *GetPhotoListRequest) (*GetPhotoListResponse, error)
	UpdatePhoto(context.Context, *UpdatePhotoRequest) (*UpdatePhotoResponse, error)
	DelPhotoByIDList(context.Context, *DelPhotoByIDListRequest) (*Empty, error)
	// --------------------------------------------------
	// tbl : timeline_events
	AddTimelineEvent(context.Context, *AddTimelineEventRequest) (*AddTimelineEventResponse, error)
	GetTimelineEventList(context.Context, *GetTimelineEventListRequest) (*GetTimelineEventListResponse, error)
	UpdateTimelineEvent(context.Context, *UpdateTimelineEventRequest) (*UpdateTimelineEventResponse, error)
	DelTimelineEventByIDList(context.Context, *DelTimelineEventByIDListRequest) (*Empty, error)
	mustEmbedUnimplementedDefaultCURDServer()
}

// UnimplementedDefaultCURDServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDefaultCURDServer struct{}

func (UnimplementedDefaultCURDServer) AddAppSetting(context.Context, *AddAppSettingRequest) (*AddAppSettingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAppSetting not implemented")
}
func (UnimplementedDefaultCURDServer) GetAppSettingList(context.Context, *GetAppSettingListRequest) (*GetAppSettingListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAppSettingList not implemented")
}
func (UnimplementedDefaultCURDServer) UpdateAppSetting(context.Context, *UpdateAppSettingRequest) (*UpdateAppSettingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAppSetting not implemented")
}
func (UnimplementedDefaultCURDServer) DelAppSettingByKeyList(context.Context, *DelAppSettingByKeyListRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelAppSettingByKeyList not implemented")
}
func (UnimplementedDefaultCURDServer) AddPhotoGroup(context.Context, *AddPhotoGroupRequest) (*AddPhotoGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPhotoGroup not implemented")
}
func (UnimplementedDefaultCURDServer) GetPhotoGroupList(context.Context, *GetPhotoGroupListRequest) (*GetPhotoGroupListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPhotoGroupList not implemented")
}
func (UnimplementedDefaultCURDServer) UpdatePhotoGroup(context.Context, *UpdatePhotoGroupRequest) (*UpdatePhotoGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePhotoGroup not implemented")
}
func (UnimplementedDefaultCURDServer) DelPhotoGroupByIDList(context.Context, *DelPhotoGroupByIDListRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelPhotoGroupByIDList not implemented")
}
func (UnimplementedDefaultCURDServer) AddPhoto(context.Context, *AddPhotoRequest) (*AddPhotoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPhoto not implemented")
}
func (UnimplementedDefaultCURDServer) GetPhotoList(context.Context, *GetPhotoListRequest) (*GetPhotoListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPhotoList not implemented")
}
func (UnimplementedDefaultCURDServer) UpdatePhoto(context.Context, *UpdatePhotoRequest) (*UpdatePhotoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePhoto not implemented")
}
func (UnimplementedDefaultCURDServer) DelPhotoByIDList(context.Context, *DelPhotoByIDListRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelPhotoByIDList not implemented")
}
func (UnimplementedDefaultCURDServer) AddTimelineEvent(context.Context, *AddTimelineEventRequest) (*AddTimelineEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTimelineEvent not implemented")
}
func (UnimplementedDefaultCURDServer) GetTimelineEventList(context.Context, *GetTimelineEventListRequest) (*GetTimelineEventListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTimelineEventList not implemented")
}
func (UnimplementedDefaultCURDServer) UpdateTimelineEvent(context.Context, *UpdateTimelineEventRequest) (*UpdateTimelineEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTimelineEvent not implemented")
}
func (UnimplementedDefaultCURDServer) DelTimelineEventByIDList(context.Context, *DelTimelineEventByIDListRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DelTimelineEventByIDList not implemented")
}
func (UnimplementedDefaultCURDServer) mustEmbedUnimplementedDefaultCURDServer() {}
func (UnimplementedDefaultCURDServer) testEmbeddedByValue()                     {}

// UnsafeDefaultCURDServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DefaultCURDServer will
// result in compilation errors.
type UnsafeDefaultCURDServer interface {
	mustEmbedUnimplementedDefaultCURDServer()
}

func RegisterDefaultCURDServer(s grpc.ServiceRegistrar, srv DefaultCURDServer) {
	// If the following call panics, it indicates UnimplementedDefaultCURDServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DefaultCURD_ServiceDesc, srv)
}

func _DefaultCURD_AddAppSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAppSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).AddAppSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_AddAppSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).AddAppSetting(ctx, req.(*AddAppSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_GetAppSettingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppSettingListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).GetAppSettingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_GetAppSettingList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).GetAppSettingList(ctx, req.(*GetAppSettingListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_UpdateAppSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAppSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).UpdateAppSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_UpdateAppSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).UpdateAppSetting(ctx, req.(*UpdateAppSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_DelAppSettingByKeyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelAppSettingByKeyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).DelAppSettingByKeyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_DelAppSettingByKeyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).DelAppSettingByKeyList(ctx, req.(*DelAppSettingByKeyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_AddPhotoGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPhotoGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).AddPhotoGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_AddPhotoGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).AddPhotoGroup(ctx, req.(*AddPhotoGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_GetPhotoGroupList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhotoGroupListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).GetPhotoGroupList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_GetPhotoGroupList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).GetPhotoGroupList(ctx, req.(*GetPhotoGroupListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_UpdatePhotoGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePhotoGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).UpdatePhotoGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_UpdatePhotoGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).UpdatePhotoGroup(ctx, req.(*UpdatePhotoGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_DelPhotoGroupByIDList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelPhotoGroupByIDListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).DelPhotoGroupByIDList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_DelPhotoGroupByIDList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).DelPhotoGroupByIDList(ctx, req.(*DelPhotoGroupByIDListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_AddPhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).AddPhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_AddPhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).AddPhoto(ctx, req.(*AddPhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_GetPhotoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhotoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).GetPhotoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_GetPhotoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).GetPhotoList(ctx, req.(*GetPhotoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_UpdatePhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).UpdatePhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_UpdatePhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).UpdatePhoto(ctx, req.(*UpdatePhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_DelPhotoByIDList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelPhotoByIDListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).DelPhotoByIDList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_DelPhotoByIDList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).DelPhotoByIDList(ctx, req.(*DelPhotoByIDListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_AddTimelineEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTimelineEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).AddTimelineEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_AddTimelineEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).AddTimelineEvent(ctx, req.(*AddTimelineEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_GetTimelineEventList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimelineEventListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).GetTimelineEventList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_GetTimelineEventList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).GetTimelineEventList(ctx, req.(*GetTimelineEventListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_UpdateTimelineEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTimelineEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).UpdateTimelineEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_UpdateTimelineEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).UpdateTimelineEvent(ctx, req.(*UpdateTimelineEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefaultCURD_DelTimelineEventByIDList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelTimelineEventByIDListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultCURDServer).DelTimelineEventByIDList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultCURD_DelTimelineEventByIDList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultCURDServer).DelTimelineEventByIDList(ctx, req.(*DelTimelineEventByIDListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DefaultCURD_ServiceDesc is the grpc.ServiceDesc for DefaultCURD service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DefaultCURD_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.defaultCURD",
	HandlerType: (*DefaultCURDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAppSetting",
			Handler:    _DefaultCURD_AddAppSetting_Handler,
		},
		{
			MethodName: "GetAppSettingList",
			Handler:    _DefaultCURD_GetAppSettingList_Handler,
		},
		{
			MethodName: "UpdateAppSetting",
			Handler:    _DefaultCURD_UpdateAppSetting_Handler,
		},
		{
			MethodName: "DelAppSettingByKeyList",
			Handler:    _DefaultCURD_DelAppSettingByKeyList_Handler,
		},
		{
			MethodName: "AddPhotoGroup",
			Handler:    _DefaultCURD_AddPhotoGroup_Handler,
		},
		{
			MethodName: "GetPhotoGroupList",
			Handler:    _DefaultCURD_GetPhotoGroupList_Handler,
		},
		{
			MethodName: "UpdatePhotoGroup",
			Handler:    _DefaultCURD_UpdatePhotoGroup_Handler,
		},
		{
			MethodName: "DelPhotoGroupByIDList",
			Handler:    _DefaultCURD_DelPhotoGroupByIDList_Handler,
		},
		{
			MethodName: "AddPhoto",
			Handler:    _DefaultCURD_AddPhoto_Handler,
		},
		{
			MethodName: "GetPhotoList",
			Handler:    _DefaultCURD_GetPhotoList_Handler,
		},
		{
			MethodName: "UpdatePhoto",
			Handler:    _DefaultCURD_UpdatePhoto_Handler,
		},
		{
			MethodName: "DelPhotoByIDList",
			Handler:    _DefaultCURD_DelPhotoByIDList_Handler,
		},
		{
			MethodName: "AddTimelineEvent",
			Handler:    _DefaultCURD_AddTimelineEvent_Handler,
		},
		{
			MethodName: "GetTimelineEventList",
			Handler:    _DefaultCURD_GetTimelineEventList_Handler,
		},
		{
			MethodName: "UpdateTimelineEvent",
			Handler:    _DefaultCURD_UpdateTimelineEvent_Handler,
		},
		{
			MethodName: "DelTimelineEventByIDList",
			Handler:    _DefaultCURD_DelTimelineEventByIDList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "z_defaultService.gen.proto",
}
