// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: z_defaultService.gen.proto

package api

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDefaultCURDAddAppSetting = "/api.defaultCURD/AddAppSetting"
const OperationDefaultCURDAddPhoto = "/api.defaultCURD/AddPhoto"
const OperationDefaultCURDAddPhotoGroup = "/api.defaultCURD/AddPhotoGroup"
const OperationDefaultCURDDelAppSettingByKeyList = "/api.defaultCURD/DelAppSettingByKeyList"
const OperationDefaultCURDDelPhotoByIDList = "/api.defaultCURD/DelPhotoByIDList"
const OperationDefaultCURDDelPhotoGroupByIDList = "/api.defaultCURD/DelPhotoGroupByIDList"
const OperationDefaultCURDGetAppSettingList = "/api.defaultCURD/GetAppSettingList"
const OperationDefaultCURDGetPhotoGroupList = "/api.defaultCURD/GetPhotoGroupList"
const OperationDefaultCURDGetPhotoList = "/api.defaultCURD/GetPhotoList"
const OperationDefaultCURDUpdateAppSetting = "/api.defaultCURD/UpdateAppSetting"
const OperationDefaultCURDUpdatePhoto = "/api.defaultCURD/UpdatePhoto"
const OperationDefaultCURDUpdatePhotoGroup = "/api.defaultCURD/UpdatePhotoGroup"

type DefaultCURDHTTPServer interface {
	// AddAppSetting --------------------------------------------------
	// tbl : app_settings
	AddAppSetting(context.Context, *AddAppSettingRequest) (*AddAppSettingResponse, error)
	// AddPhoto --------------------------------------------------
	// tbl : photos
	AddPhoto(context.Context, *AddPhotoRequest) (*AddPhotoResponse, error)
	// AddPhotoGroup --------------------------------------------------
	// tbl : photo_groups
	AddPhotoGroup(context.Context, *AddPhotoGroupRequest) (*AddPhotoGroupResponse, error)
	DelAppSettingByKeyList(context.Context, *DelAppSettingByKeyListRequest) (*Empty, error)
	DelPhotoByIDList(context.Context, *DelPhotoByIDListRequest) (*Empty, error)
	DelPhotoGroupByIDList(context.Context, *DelPhotoGroupByIDListRequest) (*Empty, error)
	GetAppSettingList(context.Context, *GetAppSettingListRequest) (*GetAppSettingListResponse, error)
	GetPhotoGroupList(context.Context, *GetPhotoGroupListRequest) (*GetPhotoGroupListResponse, error)
	GetPhotoList(context.Context, *GetPhotoListRequest) (*GetPhotoListResponse, error)
	UpdateAppSetting(context.Context, *UpdateAppSettingRequest) (*UpdateAppSettingResponse, error)
	UpdatePhoto(context.Context, *UpdatePhotoRequest) (*UpdatePhotoResponse, error)
	UpdatePhotoGroup(context.Context, *UpdatePhotoGroupRequest) (*UpdatePhotoGroupResponse, error)
}

func RegisterDefaultCURDHTTPServer(s *http.Server, srv DefaultCURDHTTPServer) {
	r := s.Route("/")
	r.POST("/app-settings", _DefaultCURD_AddAppSetting0_HTTP_Handler(srv))
	r.GET("/app-settings", _DefaultCURD_GetAppSettingList0_HTTP_Handler(srv))
	r.PATCH("/app-settings", _DefaultCURD_UpdateAppSetting0_HTTP_Handler(srv))
	r.DELETE("/app-settings", _DefaultCURD_DelAppSettingByKeyList0_HTTP_Handler(srv))
	r.POST("/photo-groups", _DefaultCURD_AddPhotoGroup0_HTTP_Handler(srv))
	r.GET("/photo-groups", _DefaultCURD_GetPhotoGroupList0_HTTP_Handler(srv))
	r.PATCH("/photo-groups", _DefaultCURD_UpdatePhotoGroup0_HTTP_Handler(srv))
	r.DELETE("/photo-groups", _DefaultCURD_DelPhotoGroupByIDList0_HTTP_Handler(srv))
	r.POST("/photos", _DefaultCURD_AddPhoto0_HTTP_Handler(srv))
	r.GET("/photos", _DefaultCURD_GetPhotoList0_HTTP_Handler(srv))
	r.PATCH("/photos", _DefaultCURD_UpdatePhoto0_HTTP_Handler(srv))
	r.DELETE("/photos", _DefaultCURD_DelPhotoByIDList0_HTTP_Handler(srv))
}

func _DefaultCURD_AddAppSetting0_HTTP_Handler(srv DefaultCURDHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddAppSettingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDefaultCURDAddAppSetting)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddAppSetting(ctx, req.(*AddAppSettingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddAppSettingResponse)
		return ctx.Result(200, reply)
	}
}

func _DefaultCURD_GetAppSettingList0_HTTP_Handler(srv DefaultCURDHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAppSettingListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDefaultCURDGetAppSettingList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAppSettingList(ctx, req.(*GetAppSettingListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAppSettingListResponse)
		return ctx.Result(200, reply)
	}
}

func _DefaultCURD_UpdateAppSetting0_HTTP_Handler(srv DefaultCURDHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAppSettingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDefaultCURDUpdateAppSetting)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAppSetting(ctx, req.(*UpdateAppSettingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateAppSettingResponse)
		return ctx.Result(200, reply)
	}
}

func _DefaultCURD_DelAppSettingByKeyList0_HTTP_Handler(srv DefaultCURDHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DelAppSettingByKeyListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDefaultCURDDelAppSettingByKeyList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DelAppSettingByKeyList(ctx, req.(*DelAppSettingByKeyListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Empty)
		return ctx.Result(200, reply)
	}
}

func _DefaultCURD_AddPhotoGroup0_HTTP_Handler(srv DefaultCURDHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddPhotoGroupRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDefaultCURDAddPhotoGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddPhotoGroup(ctx, req.(*AddPhotoGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddPhotoGroupResponse)
		return ctx.Result(200, reply)
	}
}

func _DefaultCURD_GetPhotoGroupList0_HTTP_Handler(srv DefaultCURDHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPhotoGroupListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDefaultCURDGetPhotoGroupList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPhotoGroupList(ctx, req.(*GetPhotoGroupListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPhotoGroupListResponse)
		return ctx.Result(200, reply)
	}
}

func _DefaultCURD_UpdatePhotoGroup0_HTTP_Handler(srv DefaultCURDHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePhotoGroupRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDefaultCURDUpdatePhotoGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePhotoGroup(ctx, req.(*UpdatePhotoGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdatePhotoGroupResponse)
		return ctx.Result(200, reply)
	}
}

func _DefaultCURD_DelPhotoGroupByIDList0_HTTP_Handler(srv DefaultCURDHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DelPhotoGroupByIDListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDefaultCURDDelPhotoGroupByIDList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DelPhotoGroupByIDList(ctx, req.(*DelPhotoGroupByIDListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Empty)
		return ctx.Result(200, reply)
	}
}

func _DefaultCURD_AddPhoto0_HTTP_Handler(srv DefaultCURDHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddPhotoRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDefaultCURDAddPhoto)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddPhoto(ctx, req.(*AddPhotoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddPhotoResponse)
		return ctx.Result(200, reply)
	}
}

func _DefaultCURD_GetPhotoList0_HTTP_Handler(srv DefaultCURDHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPhotoListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDefaultCURDGetPhotoList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPhotoList(ctx, req.(*GetPhotoListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPhotoListResponse)
		return ctx.Result(200, reply)
	}
}

func _DefaultCURD_UpdatePhoto0_HTTP_Handler(srv DefaultCURDHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePhotoRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDefaultCURDUpdatePhoto)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePhoto(ctx, req.(*UpdatePhotoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdatePhotoResponse)
		return ctx.Result(200, reply)
	}
}

func _DefaultCURD_DelPhotoByIDList0_HTTP_Handler(srv DefaultCURDHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DelPhotoByIDListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDefaultCURDDelPhotoByIDList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DelPhotoByIDList(ctx, req.(*DelPhotoByIDListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Empty)
		return ctx.Result(200, reply)
	}
}

type DefaultCURDHTTPClient interface {
	// AddAppSetting --------------------------------------------------
	// tbl : app_settings
	AddAppSetting(ctx context.Context, req *AddAppSettingRequest, opts ...http.CallOption) (rsp *AddAppSettingResponse, err error)
	// AddPhoto --------------------------------------------------
	// tbl : photos
	AddPhoto(ctx context.Context, req *AddPhotoRequest, opts ...http.CallOption) (rsp *AddPhotoResponse, err error)
	// AddPhotoGroup --------------------------------------------------
	// tbl : photo_groups
	AddPhotoGroup(ctx context.Context, req *AddPhotoGroupRequest, opts ...http.CallOption) (rsp *AddPhotoGroupResponse, err error)
	DelAppSettingByKeyList(ctx context.Context, req *DelAppSettingByKeyListRequest, opts ...http.CallOption) (rsp *Empty, err error)
	DelPhotoByIDList(ctx context.Context, req *DelPhotoByIDListRequest, opts ...http.CallOption) (rsp *Empty, err error)
	DelPhotoGroupByIDList(ctx context.Context, req *DelPhotoGroupByIDListRequest, opts ...http.CallOption) (rsp *Empty, err error)
	GetAppSettingList(ctx context.Context, req *GetAppSettingListRequest, opts ...http.CallOption) (rsp *GetAppSettingListResponse, err error)
	GetPhotoGroupList(ctx context.Context, req *GetPhotoGroupListRequest, opts ...http.CallOption) (rsp *GetPhotoGroupListResponse, err error)
	GetPhotoList(ctx context.Context, req *GetPhotoListRequest, opts ...http.CallOption) (rsp *GetPhotoListResponse, err error)
	UpdateAppSetting(ctx context.Context, req *UpdateAppSettingRequest, opts ...http.CallOption) (rsp *UpdateAppSettingResponse, err error)
	UpdatePhoto(ctx context.Context, req *UpdatePhotoRequest, opts ...http.CallOption) (rsp *UpdatePhotoResponse, err error)
	UpdatePhotoGroup(ctx context.Context, req *UpdatePhotoGroupRequest, opts ...http.CallOption) (rsp *UpdatePhotoGroupResponse, err error)
}

type DefaultCURDHTTPClientImpl struct {
	cc *http.Client
}

func NewDefaultCURDHTTPClient(client *http.Client) DefaultCURDHTTPClient {
	return &DefaultCURDHTTPClientImpl{client}
}

// AddAppSetting --------------------------------------------------
// tbl : app_settings
func (c *DefaultCURDHTTPClientImpl) AddAppSetting(ctx context.Context, in *AddAppSettingRequest, opts ...http.CallOption) (*AddAppSettingResponse, error) {
	var out AddAppSettingResponse
	pattern := "/app-settings"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDefaultCURDAddAppSetting))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// AddPhoto --------------------------------------------------
// tbl : photos
func (c *DefaultCURDHTTPClientImpl) AddPhoto(ctx context.Context, in *AddPhotoRequest, opts ...http.CallOption) (*AddPhotoResponse, error) {
	var out AddPhotoResponse
	pattern := "/photos"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDefaultCURDAddPhoto))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// AddPhotoGroup --------------------------------------------------
// tbl : photo_groups
func (c *DefaultCURDHTTPClientImpl) AddPhotoGroup(ctx context.Context, in *AddPhotoGroupRequest, opts ...http.CallOption) (*AddPhotoGroupResponse, error) {
	var out AddPhotoGroupResponse
	pattern := "/photo-groups"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDefaultCURDAddPhotoGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DefaultCURDHTTPClientImpl) DelAppSettingByKeyList(ctx context.Context, in *DelAppSettingByKeyListRequest, opts ...http.CallOption) (*Empty, error) {
	var out Empty
	pattern := "/app-settings"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDefaultCURDDelAppSettingByKeyList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DefaultCURDHTTPClientImpl) DelPhotoByIDList(ctx context.Context, in *DelPhotoByIDListRequest, opts ...http.CallOption) (*Empty, error) {
	var out Empty
	pattern := "/photos"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDefaultCURDDelPhotoByIDList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DefaultCURDHTTPClientImpl) DelPhotoGroupByIDList(ctx context.Context, in *DelPhotoGroupByIDListRequest, opts ...http.CallOption) (*Empty, error) {
	var out Empty
	pattern := "/photo-groups"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDefaultCURDDelPhotoGroupByIDList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DefaultCURDHTTPClientImpl) GetAppSettingList(ctx context.Context, in *GetAppSettingListRequest, opts ...http.CallOption) (*GetAppSettingListResponse, error) {
	var out GetAppSettingListResponse
	pattern := "/app-settings"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDefaultCURDGetAppSettingList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DefaultCURDHTTPClientImpl) GetPhotoGroupList(ctx context.Context, in *GetPhotoGroupListRequest, opts ...http.CallOption) (*GetPhotoGroupListResponse, error) {
	var out GetPhotoGroupListResponse
	pattern := "/photo-groups"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDefaultCURDGetPhotoGroupList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DefaultCURDHTTPClientImpl) GetPhotoList(ctx context.Context, in *GetPhotoListRequest, opts ...http.CallOption) (*GetPhotoListResponse, error) {
	var out GetPhotoListResponse
	pattern := "/photos"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDefaultCURDGetPhotoList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DefaultCURDHTTPClientImpl) UpdateAppSetting(ctx context.Context, in *UpdateAppSettingRequest, opts ...http.CallOption) (*UpdateAppSettingResponse, error) {
	var out UpdateAppSettingResponse
	pattern := "/app-settings"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDefaultCURDUpdateAppSetting))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DefaultCURDHTTPClientImpl) UpdatePhoto(ctx context.Context, in *UpdatePhotoRequest, opts ...http.CallOption) (*UpdatePhotoResponse, error) {
	var out UpdatePhotoResponse
	pattern := "/photos"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDefaultCURDUpdatePhoto))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DefaultCURDHTTPClientImpl) UpdatePhotoGroup(ctx context.Context, in *UpdatePhotoGroupRequest, opts ...http.CallOption) (*UpdatePhotoGroupResponse, error) {
	var out UpdatePhotoGroupResponse
	pattern := "/photo-groups"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDefaultCURDUpdatePhotoGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
