// Code generated by tools/genCURD. DO NOT EDIT.

package data

import (
	"backend/internal/pkg/db"
	"backend/internal/pkg/db/model"
	"backend/internal/pkg/perr"

	"github.com/pancake-lee/pgo/pkg/papp"
)

type TimelineEventDO = model.TimelineEvent

type timelineEventDAO struct{}

var TimelineEventDAO timelineEventDAO

func (*timelineEventDAO) Add(ctx *papp.AppCtx, timelineEvent *TimelineEventDO) error {
	if timelineEvent == nil {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	// TODO 用反射识别是否有create/update字段，自动赋值
	q := db.GetQuery().TimelineEvent
	err := q.WithContext(ctx).Create(timelineEvent)
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*timelineEventDAO) GetAll(ctx *papp.AppCtx,
) (timelineEventList []*TimelineEventDO, err error) {
	q := db.GetQuery().TimelineEvent
	timelineEventList, err = q.WithContext(ctx).Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return timelineEventList, nil
}

func (*timelineEventDAO) GetByIndex(ctx *papp.AppCtx,
	IDList []string,
) ([]*TimelineEventDO, error) {
	q := db.GetQuery().TimelineEvent
	do := q.WithContext(ctx)

	if len(IDList) > 0 {
		do = do.Where(q.ID.In(IDList...))
	}
	list, err := do.Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return list, nil
}

func (*timelineEventDAO) UpdateByID(ctx *papp.AppCtx, do *TimelineEventDO) error {
	if do.ID == "" {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetQuery().TimelineEvent
	_, err := q.WithContext(ctx).Where(q.ID.Eq(do.ID)).Updates(do)
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*timelineEventDAO) DelByID(ctx *papp.AppCtx, idx1 string) error {
	if idx1 == "" {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetQuery().TimelineEvent
	_, err := q.WithContext(ctx).Where(q.ID.Eq(idx1)).Delete()
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*timelineEventDAO) DelByIDList(ctx *papp.AppCtx, idx1List []string) error {
	if len(idx1List) == 0 {
		return nil
	}
	q := db.GetQuery().TimelineEvent
	_, err := q.WithContext(ctx).
		Where(q.ID.In(idx1List...)).Delete()
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*timelineEventDAO) GetByID(ctx *papp.AppCtx, idx1 string,
) (timelineEvent *TimelineEventDO, err error) {
	if idx1 == "" {
		return timelineEvent, ctx.Log.LogErr(perr.ErrParamInvalid)
	}

	q := db.GetQuery().TimelineEvent
	timelineEvent, err = q.WithContext(ctx).
		Where(q.ID.Eq(idx1)).First()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return timelineEvent, nil
}

func (*timelineEventDAO) GetByIDList(ctx *papp.AppCtx, idx1List []string,
) (timelineEventMap map[string]*TimelineEventDO, err error) {
	if len(idx1List) == 0 {
		return nil, nil
	}

	q := db.GetQuery().TimelineEvent
	l, err := q.WithContext(ctx).
		Where(q.ID.In(idx1List...)).Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	timelineEventMap = make(map[string]*TimelineEventDO)
	for _, i := range l {
		timelineEventMap[i.ID] = i
	}
	return timelineEventMap, nil
}
