// Code generated by tools/genCURD. DO NOT EDIT.

package data

import (
	"backend/internal/pkg/db"
	"backend/internal/pkg/db/model"
	"backend/internal/pkg/perr"

	"github.com/pancake-lee/pgo/pkg/papp"
)

type PhotoGroupDO = model.PhotoGroup

type photoGroupDAO struct{}

var PhotoGroupDAO photoGroupDAO

func (*photoGroupDAO) Add(ctx *papp.AppCtx, photoGroup *PhotoGroupDO) error {
	if photoGroup == nil {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	// TODO 用反射识别是否有create/update字段，自动赋值
	q := db.GetQuery().PhotoGroup
	err := q.WithContext(ctx).Create(photoGroup)
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*photoGroupDAO) GetAll(ctx *papp.AppCtx,
) (photoGroupList []*PhotoGroupDO, err error) {
	q := db.GetQuery().PhotoGroup
	photoGroupList, err = q.WithContext(ctx).Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return photoGroupList, nil
}

func (*photoGroupDAO) GetByIndex(ctx *papp.AppCtx,
IDList []string,
) ([]*PhotoGroupDO, error) {
	q := db.GetQuery().PhotoGroup
	do := q.WithContext(ctx)

	if len(IDList) > 0 {
		do = do.Where(q.ID.In(IDList...))
	}
	list, err := do.Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return list, nil
}

func (*photoGroupDAO) UpdateByID(ctx *papp.AppCtx, do *PhotoGroupDO) error {
	if do.ID == "" {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetQuery().PhotoGroup
	_, err := q.WithContext(ctx).Where(q.ID.Eq(do.ID)).Updates(do)
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*photoGroupDAO) DelByID(ctx *papp.AppCtx, idx1 string) error {
	if idx1 == "" {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetQuery().PhotoGroup
	_, err := q.WithContext(ctx).Where(q.ID.Eq(idx1)).Delete()
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*photoGroupDAO) DelByIDList(ctx *papp.AppCtx, idx1List []string) error {
	if len(idx1List) == 0 {
		return nil
	}
	q := db.GetQuery().PhotoGroup
	_, err := q.WithContext(ctx).
		Where(q.ID.In(idx1List...)).Delete()
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*photoGroupDAO) GetByID(ctx *papp.AppCtx, idx1 string,
) (photoGroup *PhotoGroupDO, err error) {
	if idx1 == "" {
		return photoGroup, ctx.Log.LogErr(perr.ErrParamInvalid)
	}

	q := db.GetQuery().PhotoGroup
	photoGroup, err = q.WithContext(ctx).
		Where(q.ID.Eq(idx1)).First()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return photoGroup, nil
}

func (*photoGroupDAO) GetByIDList(ctx *papp.AppCtx, idx1List []string,
) (photoGroupMap map[string]*PhotoGroupDO, err error) {
	if len(idx1List) == 0 {
		return nil, nil
	}

	q := db.GetQuery().PhotoGroup
	l, err := q.WithContext(ctx).
		Where(q.ID.In(idx1List...)).Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	photoGroupMap = make(map[string]*PhotoGroupDO)
	for _, i := range l {
		photoGroupMap[i.ID] = i
	}
	return photoGroupMap, nil
}

