// Code generated by tools/genCURD. DO NOT EDIT.

package data

import (
	"backend/internal/pkg/db"
	"backend/internal/pkg/db/model"
	"backend/internal/pkg/perr"

	"github.com/pancake-lee/pgo/pkg/papp"
)

type AppSettingDO = model.AppSetting

type appSettingDAO struct{}

var AppSettingDAO appSettingDAO

func (*appSettingDAO) Add(ctx *papp.AppCtx, appSetting *AppSettingDO) error {
	if appSetting == nil {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	// TODO 用反射识别是否有create/update字段，自动赋值
	q := db.GetQuery().AppSetting
	err := q.WithContext(ctx).Create(appSetting)
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*appSettingDAO) GetAll(ctx *papp.AppCtx,
) (appSettingList []*AppSettingDO, err error) {
	q := db.GetQuery().AppSetting
	appSettingList, err = q.WithContext(ctx).Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return appSettingList, nil
}

func (*appSettingDAO) GetByIndex(ctx *papp.AppCtx,
keyList []string,
) ([]*AppSettingDO, error) {
	q := db.GetQuery().AppSetting
	do := q.WithContext(ctx)

	if len(keyList) > 0 {
		do = do.Where(q.Key.In(keyList...))
	}
	list, err := do.Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return list, nil
}

func (*appSettingDAO) UpdateByKey(ctx *papp.AppCtx, do *AppSettingDO) error {
	if do.Key == "" {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetQuery().AppSetting
	_, err := q.WithContext(ctx).Where(q.Key.Eq(do.Key)).Updates(do)
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*appSettingDAO) DelByKey(ctx *papp.AppCtx, idx1 string) error {
	if idx1 == "" {
		return ctx.Log.LogErr(perr.ErrParamInvalid)
	}
	q := db.GetQuery().AppSetting
	_, err := q.WithContext(ctx).Where(q.Key.Eq(idx1)).Delete()
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*appSettingDAO) DelByKeyList(ctx *papp.AppCtx, idx1List []string) error {
	if len(idx1List) == 0 {
		return nil
	}
	q := db.GetQuery().AppSetting
	_, err := q.WithContext(ctx).
		Where(q.Key.In(idx1List...)).Delete()
	if err != nil {
		return ctx.Log.LogErr(err)
	}
	return nil
}

func (*appSettingDAO) GetByKey(ctx *papp.AppCtx, idx1 string,
) (appSetting *AppSettingDO, err error) {
	if idx1 == "" {
		return appSetting, ctx.Log.LogErr(perr.ErrParamInvalid)
	}

	q := db.GetQuery().AppSetting
	appSetting, err = q.WithContext(ctx).
		Where(q.Key.Eq(idx1)).First()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	return appSetting, nil
}

func (*appSettingDAO) GetByKeyList(ctx *papp.AppCtx, idx1List []string,
) (appSettingMap map[string]*AppSettingDO, err error) {
	if len(idx1List) == 0 {
		return nil, nil
	}

	q := db.GetQuery().AppSetting
	l, err := q.WithContext(ctx).
		Where(q.Key.In(idx1List...)).Find()
	if err != nil {
		return nil, ctx.Log.LogErr(err)
	}
	appSettingMap = make(map[string]*AppSettingDO)
	for _, i := range l {
		appSettingMap[i.Key] = i
	}
	return appSettingMap, nil
}

