# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApiPhotoSegment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'str',
        'label': 'str',
        'count': 'str',
        'offset': 'str'
    }

    attribute_map = {
        'key': 'key',
        'label': 'label',
        'count': 'count',
        'offset': 'offset'
    }

    def __init__(self, key=None, label=None, count=None, offset=None):  # noqa: E501
        """ApiPhotoSegment - a model defined in Swagger"""  # noqa: E501
        self._key = None
        self._label = None
        self._count = None
        self._offset = None
        self.discriminator = None
        if key is not None:
            self.key = key
        if label is not None:
            self.label = label
        if count is not None:
            self.count = count
        if offset is not None:
            self.offset = offset

    @property
    def key(self):
        """Gets the key of this ApiPhotoSegment.  # noqa: E501


        :return: The key of this ApiPhotoSegment.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this ApiPhotoSegment.


        :param key: The key of this ApiPhotoSegment.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def label(self):
        """Gets the label of this ApiPhotoSegment.  # noqa: E501


        :return: The label of this ApiPhotoSegment.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this ApiPhotoSegment.


        :param label: The label of this ApiPhotoSegment.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def count(self):
        """Gets the count of this ApiPhotoSegment.  # noqa: E501


        :return: The count of this ApiPhotoSegment.  # noqa: E501
        :rtype: str
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this ApiPhotoSegment.


        :param count: The count of this ApiPhotoSegment.  # noqa: E501
        :type: str
        """

        self._count = count

    @property
    def offset(self):
        """Gets the offset of this ApiPhotoSegment.  # noqa: E501


        :return: The offset of this ApiPhotoSegment.  # noqa: E501
        :rtype: str
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this ApiPhotoSegment.


        :param offset: The offset of this ApiPhotoSegment.  # noqa: E501
        :type: str
        """

        self._offset = offset

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiPhotoSegment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiPhotoSegment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
