# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApiAbandonCodeInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'idx1': 'int',
        'col1': 'str'
    }

    attribute_map = {
        'idx1': 'idx1',
        'col1': 'col1'
    }

    def __init__(self, idx1=None, col1=None):  # noqa: E501
        """ApiAbandonCodeInfo - a model defined in Swagger"""  # noqa: E501
        self._idx1 = None
        self._col1 = None
        self.discriminator = None
        if idx1 is not None:
            self.idx1 = idx1
        if col1 is not None:
            self.col1 = col1

    @property
    def idx1(self):
        """Gets the idx1 of this ApiAbandonCodeInfo.  # noqa: E501

        MARK REPLACE PB COL START 替换内容，所有字段  # noqa: E501

        :return: The idx1 of this ApiAbandonCodeInfo.  # noqa: E501
        :rtype: int
        """
        return self._idx1

    @idx1.setter
    def idx1(self, idx1):
        """Sets the idx1 of this ApiAbandonCodeInfo.

        MARK REPLACE PB COL START 替换内容，所有字段  # noqa: E501

        :param idx1: The idx1 of this ApiAbandonCodeInfo.  # noqa: E501
        :type: int
        """

        self._idx1 = idx1

    @property
    def col1(self):
        """Gets the col1 of this ApiAbandonCodeInfo.  # noqa: E501


        :return: The col1 of this ApiAbandonCodeInfo.  # noqa: E501
        :rtype: str
        """
        return self._col1

    @col1.setter
    def col1(self, col1):
        """Sets the col1 of this ApiAbandonCodeInfo.


        :param col1: The col1 of this ApiAbandonCodeInfo.  # noqa: E501
        :type: str
        """

        self._col1 = col1

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiAbandonCodeInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiAbandonCodeInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
