# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApiGetDescribeProgressResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'processing_ids': 'list[str]'
    }

    attribute_map = {
        'processing_ids': 'processingIds'
    }

    def __init__(self, processing_ids=None):  # noqa: E501
        """ApiGetDescribeProgressResponse - a model defined in Swagger"""  # noqa: E501
        self._processing_ids = None
        self.discriminator = None
        if processing_ids is not None:
            self.processing_ids = processing_ids

    @property
    def processing_ids(self):
        """Gets the processing_ids of this ApiGetDescribeProgressResponse.  # noqa: E501


        :return: The processing_ids of this ApiGetDescribeProgressResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._processing_ids

    @processing_ids.setter
    def processing_ids(self, processing_ids):
        """Sets the processing_ids of this ApiGetDescribeProgressResponse.


        :param processing_ids: The processing_ids of this ApiGetDescribeProgressResponse.  # noqa: E501
        :type: list[str]
        """

        self._processing_ids = processing_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiGetDescribeProgressResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiGetDescribeProgressResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
