# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApiTimelineEventInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'event_date': 'str',
        'event': 'str',
        'note': 'str',
        'created_at': 'str',
        'updated_at': 'str'
    }

    attribute_map = {
        'id': 'ID',
        'event_date': 'eventDate',
        'event': 'event',
        'note': 'note',
        'created_at': 'createdAt',
        'updated_at': 'updatedAt'
    }

    def __init__(self, id=None, event_date=None, event=None, note=None, created_at=None, updated_at=None):  # noqa: E501
        """ApiTimelineEventInfo - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._event_date = None
        self._event = None
        self._note = None
        self._created_at = None
        self._updated_at = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if event_date is not None:
            self.event_date = event_date
        if event is not None:
            self.event = event
        if note is not None:
            self.note = note
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def id(self):
        """Gets the id of this ApiTimelineEventInfo.  # noqa: E501


        :return: The id of this ApiTimelineEventInfo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApiTimelineEventInfo.


        :param id: The id of this ApiTimelineEventInfo.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def event_date(self):
        """Gets the event_date of this ApiTimelineEventInfo.  # noqa: E501


        :return: The event_date of this ApiTimelineEventInfo.  # noqa: E501
        :rtype: str
        """
        return self._event_date

    @event_date.setter
    def event_date(self, event_date):
        """Sets the event_date of this ApiTimelineEventInfo.


        :param event_date: The event_date of this ApiTimelineEventInfo.  # noqa: E501
        :type: str
        """

        self._event_date = event_date

    @property
    def event(self):
        """Gets the event of this ApiTimelineEventInfo.  # noqa: E501


        :return: The event of this ApiTimelineEventInfo.  # noqa: E501
        :rtype: str
        """
        return self._event

    @event.setter
    def event(self, event):
        """Sets the event of this ApiTimelineEventInfo.


        :param event: The event of this ApiTimelineEventInfo.  # noqa: E501
        :type: str
        """

        self._event = event

    @property
    def note(self):
        """Gets the note of this ApiTimelineEventInfo.  # noqa: E501


        :return: The note of this ApiTimelineEventInfo.  # noqa: E501
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this ApiTimelineEventInfo.


        :param note: The note of this ApiTimelineEventInfo.  # noqa: E501
        :type: str
        """

        self._note = note

    @property
    def created_at(self):
        """Gets the created_at of this ApiTimelineEventInfo.  # noqa: E501


        :return: The created_at of this ApiTimelineEventInfo.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ApiTimelineEventInfo.


        :param created_at: The created_at of this ApiTimelineEventInfo.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this ApiTimelineEventInfo.  # noqa: E501


        :return: The updated_at of this ApiTimelineEventInfo.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ApiTimelineEventInfo.


        :param updated_at: The updated_at of this ApiTimelineEventInfo.  # noqa: E501
        :type: str
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiTimelineEventInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiTimelineEventInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
