# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApiAppSettingInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'str',
        'value': 'str',
        'updated_at': 'str'
    }

    attribute_map = {
        'key': 'key',
        'value': 'value',
        'updated_at': 'updatedAt'
    }

    def __init__(self, key=None, value=None, updated_at=None):  # noqa: E501
        """ApiAppSettingInfo - a model defined in Swagger"""  # noqa: E501
        self._key = None
        self._value = None
        self._updated_at = None
        self.discriminator = None
        if key is not None:
            self.key = key
        if value is not None:
            self.value = value
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def key(self):
        """Gets the key of this ApiAppSettingInfo.  # noqa: E501


        :return: The key of this ApiAppSettingInfo.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this ApiAppSettingInfo.


        :param key: The key of this ApiAppSettingInfo.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def value(self):
        """Gets the value of this ApiAppSettingInfo.  # noqa: E501


        :return: The value of this ApiAppSettingInfo.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ApiAppSettingInfo.


        :param value: The value of this ApiAppSettingInfo.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def updated_at(self):
        """Gets the updated_at of this ApiAppSettingInfo.  # noqa: E501


        :return: The updated_at of this ApiAppSettingInfo.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ApiAppSettingInfo.


        :param updated_at: The updated_at of this ApiAppSettingInfo.  # noqa: E501
        :type: str
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiAppSettingInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiAppSettingInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
