# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApiAttributeValues(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'objects': 'list[str]',
        'colors': 'list[str]',
        'scene': 'list[str]',
        'lighting': 'list[str]',
        'mood': 'list[str]',
        'composition': 'list[str]'
    }

    attribute_map = {
        'objects': 'objects',
        'colors': 'colors',
        'scene': 'scene',
        'lighting': 'lighting',
        'mood': 'mood',
        'composition': 'composition'
    }

    def __init__(self, objects=None, colors=None, scene=None, lighting=None, mood=None, composition=None):  # noqa: E501
        """ApiAttributeValues - a model defined in Swagger"""  # noqa: E501
        self._objects = None
        self._colors = None
        self._scene = None
        self._lighting = None
        self._mood = None
        self._composition = None
        self.discriminator = None
        if objects is not None:
            self.objects = objects
        if colors is not None:
            self.colors = colors
        if scene is not None:
            self.scene = scene
        if lighting is not None:
            self.lighting = lighting
        if mood is not None:
            self.mood = mood
        if composition is not None:
            self.composition = composition

    @property
    def objects(self):
        """Gets the objects of this ApiAttributeValues.  # noqa: E501


        :return: The objects of this ApiAttributeValues.  # noqa: E501
        :rtype: list[str]
        """
        return self._objects

    @objects.setter
    def objects(self, objects):
        """Sets the objects of this ApiAttributeValues.


        :param objects: The objects of this ApiAttributeValues.  # noqa: E501
        :type: list[str]
        """

        self._objects = objects

    @property
    def colors(self):
        """Gets the colors of this ApiAttributeValues.  # noqa: E501


        :return: The colors of this ApiAttributeValues.  # noqa: E501
        :rtype: list[str]
        """
        return self._colors

    @colors.setter
    def colors(self, colors):
        """Sets the colors of this ApiAttributeValues.


        :param colors: The colors of this ApiAttributeValues.  # noqa: E501
        :type: list[str]
        """

        self._colors = colors

    @property
    def scene(self):
        """Gets the scene of this ApiAttributeValues.  # noqa: E501


        :return: The scene of this ApiAttributeValues.  # noqa: E501
        :rtype: list[str]
        """
        return self._scene

    @scene.setter
    def scene(self, scene):
        """Sets the scene of this ApiAttributeValues.


        :param scene: The scene of this ApiAttributeValues.  # noqa: E501
        :type: list[str]
        """

        self._scene = scene

    @property
    def lighting(self):
        """Gets the lighting of this ApiAttributeValues.  # noqa: E501


        :return: The lighting of this ApiAttributeValues.  # noqa: E501
        :rtype: list[str]
        """
        return self._lighting

    @lighting.setter
    def lighting(self, lighting):
        """Sets the lighting of this ApiAttributeValues.


        :param lighting: The lighting of this ApiAttributeValues.  # noqa: E501
        :type: list[str]
        """

        self._lighting = lighting

    @property
    def mood(self):
        """Gets the mood of this ApiAttributeValues.  # noqa: E501


        :return: The mood of this ApiAttributeValues.  # noqa: E501
        :rtype: list[str]
        """
        return self._mood

    @mood.setter
    def mood(self, mood):
        """Sets the mood of this ApiAttributeValues.


        :param mood: The mood of this ApiAttributeValues.  # noqa: E501
        :type: list[str]
        """

        self._mood = mood

    @property
    def composition(self):
        """Gets the composition of this ApiAttributeValues.  # noqa: E501


        :return: The composition of this ApiAttributeValues.  # noqa: E501
        :rtype: list[str]
        """
        return self._composition

    @composition.setter
    def composition(self, composition):
        """Sets the composition of this ApiAttributeValues.


        :param composition: The composition of this ApiAttributeValues.  # noqa: E501
        :type: list[str]
        """

        self._composition = composition

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiAttributeValues, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiAttributeValues):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
