# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApiGetBurstGroupsConfigResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fine': 'ApiBurstProfileConfig',
        'coarse': 'ApiBurstProfileConfig'
    }

    attribute_map = {
        'fine': 'fine',
        'coarse': 'coarse'
    }

    def __init__(self, fine=None, coarse=None):  # noqa: E501
        """ApiGetBurstGroupsConfigResponse - a model defined in Swagger"""  # noqa: E501
        self._fine = None
        self._coarse = None
        self.discriminator = None
        if fine is not None:
            self.fine = fine
        if coarse is not None:
            self.coarse = coarse

    @property
    def fine(self):
        """Gets the fine of this ApiGetBurstGroupsConfigResponse.  # noqa: E501


        :return: The fine of this ApiGetBurstGroupsConfigResponse.  # noqa: E501
        :rtype: ApiBurstProfileConfig
        """
        return self._fine

    @fine.setter
    def fine(self, fine):
        """Sets the fine of this ApiGetBurstGroupsConfigResponse.


        :param fine: The fine of this ApiGetBurstGroupsConfigResponse.  # noqa: E501
        :type: ApiBurstProfileConfig
        """

        self._fine = fine

    @property
    def coarse(self):
        """Gets the coarse of this ApiGetBurstGroupsConfigResponse.  # noqa: E501


        :return: The coarse of this ApiGetBurstGroupsConfigResponse.  # noqa: E501
        :rtype: ApiBurstProfileConfig
        """
        return self._coarse

    @coarse.setter
    def coarse(self, coarse):
        """Sets the coarse of this ApiGetBurstGroupsConfigResponse.


        :param coarse: The coarse of this ApiGetBurstGroupsConfigResponse.  # noqa: E501
        :type: ApiBurstProfileConfig
        """

        self._coarse = coarse

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiGetBurstGroupsConfigResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiGetBurstGroupsConfigResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
