# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApiUpdatePhotoGroupResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'photo_group': 'ApiPhotoGroupInfo'
    }

    attribute_map = {
        'photo_group': 'photoGroup'
    }

    def __init__(self, photo_group=None):  # noqa: E501
        """ApiUpdatePhotoGroupResponse - a model defined in Swagger"""  # noqa: E501
        self._photo_group = None
        self.discriminator = None
        if photo_group is not None:
            self.photo_group = photo_group

    @property
    def photo_group(self):
        """Gets the photo_group of this ApiUpdatePhotoGroupResponse.  # noqa: E501


        :return: The photo_group of this ApiUpdatePhotoGroupResponse.  # noqa: E501
        :rtype: ApiPhotoGroupInfo
        """
        return self._photo_group

    @photo_group.setter
    def photo_group(self, photo_group):
        """Sets the photo_group of this ApiUpdatePhotoGroupResponse.


        :param photo_group: The photo_group of this ApiUpdatePhotoGroupResponse.  # noqa: E501
        :type: ApiPhotoGroupInfo
        """

        self._photo_group = photo_group

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiUpdatePhotoGroupResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiUpdatePhotoGroupResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
