# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApiPhotoInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'filename': 'str',
        'file_path': 'str',
        'file_type': 'str',
        'timeline': 'str',
        'tags': 'str',
        'description': 'str',
        'objects': 'str',
        'colors': 'str',
        'scene': 'str',
        'lighting': 'str',
        'mood': 'str',
        'composition': 'str',
        'shot_at': 'str',
        'width': 'int',
        'height': 'int',
        'brand': 'str',
        'model': 'str',
        'lens': 'str',
        'focal_length': 'str',
        'aperture': 'str',
        'iso': 'int',
        'exposure_time': 'str',
        'latitude': 'float',
        'longitude': 'float',
        'altitude': 'float',
        'burst_group_id': 'str',
        'burst_group_coarse_id': 'str',
        'imported_at': 'str'
    }

    attribute_map = {
        'id': 'ID',
        'filename': 'filename',
        'file_path': 'filePath',
        'file_type': 'fileType',
        'timeline': 'timeline',
        'tags': 'tags',
        'description': 'description',
        'objects': 'objects',
        'colors': 'colors',
        'scene': 'scene',
        'lighting': 'lighting',
        'mood': 'mood',
        'composition': 'composition',
        'shot_at': 'shotAt',
        'width': 'width',
        'height': 'height',
        'brand': 'brand',
        'model': 'model',
        'lens': 'lens',
        'focal_length': 'focalLength',
        'aperture': 'aperture',
        'iso': 'iso',
        'exposure_time': 'exposureTime',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'altitude': 'altitude',
        'burst_group_id': 'burstGroupID',
        'burst_group_coarse_id': 'burstGroupCoarseID',
        'imported_at': 'importedAt'
    }

    def __init__(self, id=None, filename=None, file_path=None, file_type=None, timeline=None, tags=None, description=None, objects=None, colors=None, scene=None, lighting=None, mood=None, composition=None, shot_at=None, width=None, height=None, brand=None, model=None, lens=None, focal_length=None, aperture=None, iso=None, exposure_time=None, latitude=None, longitude=None, altitude=None, burst_group_id=None, burst_group_coarse_id=None, imported_at=None):  # noqa: E501
        """ApiPhotoInfo - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._filename = None
        self._file_path = None
        self._file_type = None
        self._timeline = None
        self._tags = None
        self._description = None
        self._objects = None
        self._colors = None
        self._scene = None
        self._lighting = None
        self._mood = None
        self._composition = None
        self._shot_at = None
        self._width = None
        self._height = None
        self._brand = None
        self._model = None
        self._lens = None
        self._focal_length = None
        self._aperture = None
        self._iso = None
        self._exposure_time = None
        self._latitude = None
        self._longitude = None
        self._altitude = None
        self._burst_group_id = None
        self._burst_group_coarse_id = None
        self._imported_at = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if filename is not None:
            self.filename = filename
        if file_path is not None:
            self.file_path = file_path
        if file_type is not None:
            self.file_type = file_type
        if timeline is not None:
            self.timeline = timeline
        if tags is not None:
            self.tags = tags
        if description is not None:
            self.description = description
        if objects is not None:
            self.objects = objects
        if colors is not None:
            self.colors = colors
        if scene is not None:
            self.scene = scene
        if lighting is not None:
            self.lighting = lighting
        if mood is not None:
            self.mood = mood
        if composition is not None:
            self.composition = composition
        if shot_at is not None:
            self.shot_at = shot_at
        if width is not None:
            self.width = width
        if height is not None:
            self.height = height
        if brand is not None:
            self.brand = brand
        if model is not None:
            self.model = model
        if lens is not None:
            self.lens = lens
        if focal_length is not None:
            self.focal_length = focal_length
        if aperture is not None:
            self.aperture = aperture
        if iso is not None:
            self.iso = iso
        if exposure_time is not None:
            self.exposure_time = exposure_time
        if latitude is not None:
            self.latitude = latitude
        if longitude is not None:
            self.longitude = longitude
        if altitude is not None:
            self.altitude = altitude
        if burst_group_id is not None:
            self.burst_group_id = burst_group_id
        if burst_group_coarse_id is not None:
            self.burst_group_coarse_id = burst_group_coarse_id
        if imported_at is not None:
            self.imported_at = imported_at

    @property
    def id(self):
        """Gets the id of this ApiPhotoInfo.  # noqa: E501


        :return: The id of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApiPhotoInfo.


        :param id: The id of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def filename(self):
        """Gets the filename of this ApiPhotoInfo.  # noqa: E501


        :return: The filename of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename):
        """Sets the filename of this ApiPhotoInfo.


        :param filename: The filename of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._filename = filename

    @property
    def file_path(self):
        """Gets the file_path of this ApiPhotoInfo.  # noqa: E501


        :return: The file_path of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._file_path

    @file_path.setter
    def file_path(self, file_path):
        """Sets the file_path of this ApiPhotoInfo.


        :param file_path: The file_path of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._file_path = file_path

    @property
    def file_type(self):
        """Gets the file_type of this ApiPhotoInfo.  # noqa: E501


        :return: The file_type of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._file_type

    @file_type.setter
    def file_type(self, file_type):
        """Sets the file_type of this ApiPhotoInfo.


        :param file_type: The file_type of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._file_type = file_type

    @property
    def timeline(self):
        """Gets the timeline of this ApiPhotoInfo.  # noqa: E501


        :return: The timeline of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._timeline

    @timeline.setter
    def timeline(self, timeline):
        """Sets the timeline of this ApiPhotoInfo.


        :param timeline: The timeline of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._timeline = timeline

    @property
    def tags(self):
        """Gets the tags of this ApiPhotoInfo.  # noqa: E501


        :return: The tags of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this ApiPhotoInfo.


        :param tags: The tags of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._tags = tags

    @property
    def description(self):
        """Gets the description of this ApiPhotoInfo.  # noqa: E501


        :return: The description of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ApiPhotoInfo.


        :param description: The description of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def objects(self):
        """Gets the objects of this ApiPhotoInfo.  # noqa: E501


        :return: The objects of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._objects

    @objects.setter
    def objects(self, objects):
        """Sets the objects of this ApiPhotoInfo.


        :param objects: The objects of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._objects = objects

    @property
    def colors(self):
        """Gets the colors of this ApiPhotoInfo.  # noqa: E501


        :return: The colors of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._colors

    @colors.setter
    def colors(self, colors):
        """Sets the colors of this ApiPhotoInfo.


        :param colors: The colors of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._colors = colors

    @property
    def scene(self):
        """Gets the scene of this ApiPhotoInfo.  # noqa: E501


        :return: The scene of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._scene

    @scene.setter
    def scene(self, scene):
        """Sets the scene of this ApiPhotoInfo.


        :param scene: The scene of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._scene = scene

    @property
    def lighting(self):
        """Gets the lighting of this ApiPhotoInfo.  # noqa: E501


        :return: The lighting of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._lighting

    @lighting.setter
    def lighting(self, lighting):
        """Sets the lighting of this ApiPhotoInfo.


        :param lighting: The lighting of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._lighting = lighting

    @property
    def mood(self):
        """Gets the mood of this ApiPhotoInfo.  # noqa: E501


        :return: The mood of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._mood

    @mood.setter
    def mood(self, mood):
        """Sets the mood of this ApiPhotoInfo.


        :param mood: The mood of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._mood = mood

    @property
    def composition(self):
        """Gets the composition of this ApiPhotoInfo.  # noqa: E501


        :return: The composition of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._composition

    @composition.setter
    def composition(self, composition):
        """Sets the composition of this ApiPhotoInfo.


        :param composition: The composition of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._composition = composition

    @property
    def shot_at(self):
        """Gets the shot_at of this ApiPhotoInfo.  # noqa: E501


        :return: The shot_at of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._shot_at

    @shot_at.setter
    def shot_at(self, shot_at):
        """Sets the shot_at of this ApiPhotoInfo.


        :param shot_at: The shot_at of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._shot_at = shot_at

    @property
    def width(self):
        """Gets the width of this ApiPhotoInfo.  # noqa: E501


        :return: The width of this ApiPhotoInfo.  # noqa: E501
        :rtype: int
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this ApiPhotoInfo.


        :param width: The width of this ApiPhotoInfo.  # noqa: E501
        :type: int
        """

        self._width = width

    @property
    def height(self):
        """Gets the height of this ApiPhotoInfo.  # noqa: E501


        :return: The height of this ApiPhotoInfo.  # noqa: E501
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this ApiPhotoInfo.


        :param height: The height of this ApiPhotoInfo.  # noqa: E501
        :type: int
        """

        self._height = height

    @property
    def brand(self):
        """Gets the brand of this ApiPhotoInfo.  # noqa: E501


        :return: The brand of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._brand

    @brand.setter
    def brand(self, brand):
        """Sets the brand of this ApiPhotoInfo.


        :param brand: The brand of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._brand = brand

    @property
    def model(self):
        """Gets the model of this ApiPhotoInfo.  # noqa: E501


        :return: The model of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this ApiPhotoInfo.


        :param model: The model of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._model = model

    @property
    def lens(self):
        """Gets the lens of this ApiPhotoInfo.  # noqa: E501


        :return: The lens of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._lens

    @lens.setter
    def lens(self, lens):
        """Sets the lens of this ApiPhotoInfo.


        :param lens: The lens of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._lens = lens

    @property
    def focal_length(self):
        """Gets the focal_length of this ApiPhotoInfo.  # noqa: E501


        :return: The focal_length of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._focal_length

    @focal_length.setter
    def focal_length(self, focal_length):
        """Sets the focal_length of this ApiPhotoInfo.


        :param focal_length: The focal_length of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._focal_length = focal_length

    @property
    def aperture(self):
        """Gets the aperture of this ApiPhotoInfo.  # noqa: E501


        :return: The aperture of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._aperture

    @aperture.setter
    def aperture(self, aperture):
        """Sets the aperture of this ApiPhotoInfo.


        :param aperture: The aperture of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._aperture = aperture

    @property
    def iso(self):
        """Gets the iso of this ApiPhotoInfo.  # noqa: E501


        :return: The iso of this ApiPhotoInfo.  # noqa: E501
        :rtype: int
        """
        return self._iso

    @iso.setter
    def iso(self, iso):
        """Sets the iso of this ApiPhotoInfo.


        :param iso: The iso of this ApiPhotoInfo.  # noqa: E501
        :type: int
        """

        self._iso = iso

    @property
    def exposure_time(self):
        """Gets the exposure_time of this ApiPhotoInfo.  # noqa: E501


        :return: The exposure_time of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._exposure_time

    @exposure_time.setter
    def exposure_time(self, exposure_time):
        """Sets the exposure_time of this ApiPhotoInfo.


        :param exposure_time: The exposure_time of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._exposure_time = exposure_time

    @property
    def latitude(self):
        """Gets the latitude of this ApiPhotoInfo.  # noqa: E501


        :return: The latitude of this ApiPhotoInfo.  # noqa: E501
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this ApiPhotoInfo.


        :param latitude: The latitude of this ApiPhotoInfo.  # noqa: E501
        :type: float
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this ApiPhotoInfo.  # noqa: E501


        :return: The longitude of this ApiPhotoInfo.  # noqa: E501
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this ApiPhotoInfo.


        :param longitude: The longitude of this ApiPhotoInfo.  # noqa: E501
        :type: float
        """

        self._longitude = longitude

    @property
    def altitude(self):
        """Gets the altitude of this ApiPhotoInfo.  # noqa: E501


        :return: The altitude of this ApiPhotoInfo.  # noqa: E501
        :rtype: float
        """
        return self._altitude

    @altitude.setter
    def altitude(self, altitude):
        """Sets the altitude of this ApiPhotoInfo.


        :param altitude: The altitude of this ApiPhotoInfo.  # noqa: E501
        :type: float
        """

        self._altitude = altitude

    @property
    def burst_group_id(self):
        """Gets the burst_group_id of this ApiPhotoInfo.  # noqa: E501


        :return: The burst_group_id of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._burst_group_id

    @burst_group_id.setter
    def burst_group_id(self, burst_group_id):
        """Sets the burst_group_id of this ApiPhotoInfo.


        :param burst_group_id: The burst_group_id of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._burst_group_id = burst_group_id

    @property
    def burst_group_coarse_id(self):
        """Gets the burst_group_coarse_id of this ApiPhotoInfo.  # noqa: E501


        :return: The burst_group_coarse_id of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._burst_group_coarse_id

    @burst_group_coarse_id.setter
    def burst_group_coarse_id(self, burst_group_coarse_id):
        """Sets the burst_group_coarse_id of this ApiPhotoInfo.


        :param burst_group_coarse_id: The burst_group_coarse_id of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._burst_group_coarse_id = burst_group_coarse_id

    @property
    def imported_at(self):
        """Gets the imported_at of this ApiPhotoInfo.  # noqa: E501


        :return: The imported_at of this ApiPhotoInfo.  # noqa: E501
        :rtype: str
        """
        return self._imported_at

    @imported_at.setter
    def imported_at(self, imported_at):
        """Sets the imported_at of this ApiPhotoInfo.


        :param imported_at: The imported_at of this ApiPhotoInfo.  # noqa: E501
        :type: str
        """

        self._imported_at = imported_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiPhotoInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiPhotoInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
