# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApiSchemaField(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'go_type': 'str',
        'sql_type': 'str',
        'json_tag': 'str',
        'gorm_tag': 'str',
        'nullable': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'go_type': 'goType',
        'sql_type': 'sqlType',
        'json_tag': 'jsonTag',
        'gorm_tag': 'gormTag',
        'nullable': 'nullable'
    }

    def __init__(self, name=None, go_type=None, sql_type=None, json_tag=None, gorm_tag=None, nullable=None):  # noqa: E501
        """ApiSchemaField - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._go_type = None
        self._sql_type = None
        self._json_tag = None
        self._gorm_tag = None
        self._nullable = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if go_type is not None:
            self.go_type = go_type
        if sql_type is not None:
            self.sql_type = sql_type
        if json_tag is not None:
            self.json_tag = json_tag
        if gorm_tag is not None:
            self.gorm_tag = gorm_tag
        if nullable is not None:
            self.nullable = nullable

    @property
    def name(self):
        """Gets the name of this ApiSchemaField.  # noqa: E501


        :return: The name of this ApiSchemaField.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApiSchemaField.


        :param name: The name of this ApiSchemaField.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def go_type(self):
        """Gets the go_type of this ApiSchemaField.  # noqa: E501


        :return: The go_type of this ApiSchemaField.  # noqa: E501
        :rtype: str
        """
        return self._go_type

    @go_type.setter
    def go_type(self, go_type):
        """Sets the go_type of this ApiSchemaField.


        :param go_type: The go_type of this ApiSchemaField.  # noqa: E501
        :type: str
        """

        self._go_type = go_type

    @property
    def sql_type(self):
        """Gets the sql_type of this ApiSchemaField.  # noqa: E501


        :return: The sql_type of this ApiSchemaField.  # noqa: E501
        :rtype: str
        """
        return self._sql_type

    @sql_type.setter
    def sql_type(self, sql_type):
        """Sets the sql_type of this ApiSchemaField.


        :param sql_type: The sql_type of this ApiSchemaField.  # noqa: E501
        :type: str
        """

        self._sql_type = sql_type

    @property
    def json_tag(self):
        """Gets the json_tag of this ApiSchemaField.  # noqa: E501


        :return: The json_tag of this ApiSchemaField.  # noqa: E501
        :rtype: str
        """
        return self._json_tag

    @json_tag.setter
    def json_tag(self, json_tag):
        """Sets the json_tag of this ApiSchemaField.


        :param json_tag: The json_tag of this ApiSchemaField.  # noqa: E501
        :type: str
        """

        self._json_tag = json_tag

    @property
    def gorm_tag(self):
        """Gets the gorm_tag of this ApiSchemaField.  # noqa: E501


        :return: The gorm_tag of this ApiSchemaField.  # noqa: E501
        :rtype: str
        """
        return self._gorm_tag

    @gorm_tag.setter
    def gorm_tag(self, gorm_tag):
        """Sets the gorm_tag of this ApiSchemaField.


        :param gorm_tag: The gorm_tag of this ApiSchemaField.  # noqa: E501
        :type: str
        """

        self._gorm_tag = gorm_tag

    @property
    def nullable(self):
        """Gets the nullable of this ApiSchemaField.  # noqa: E501


        :return: The nullable of this ApiSchemaField.  # noqa: E501
        :rtype: bool
        """
        return self._nullable

    @nullable.setter
    def nullable(self, nullable):
        """Sets the nullable of this ApiSchemaField.


        :param nullable: The nullable of this ApiSchemaField.  # noqa: E501
        :type: bool
        """

        self._nullable = nullable

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiSchemaField, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiSchemaField):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
