# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApiTimelineEventDetail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        '_date': 'str',
        'event': 'str',
        'note': 'str',
        'photo_count': 'int',
        'is_scattered': 'bool'
    }

    attribute_map = {
        'id': 'id',
        '_date': 'date',
        'event': 'event',
        'note': 'note',
        'photo_count': 'photoCount',
        'is_scattered': 'isScattered'
    }

    def __init__(self, id=None, _date=None, event=None, note=None, photo_count=None, is_scattered=None):  # noqa: E501
        """ApiTimelineEventDetail - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self.__date = None
        self._event = None
        self._note = None
        self._photo_count = None
        self._is_scattered = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if _date is not None:
            self._date = _date
        if event is not None:
            self.event = event
        if note is not None:
            self.note = note
        if photo_count is not None:
            self.photo_count = photo_count
        if is_scattered is not None:
            self.is_scattered = is_scattered

    @property
    def id(self):
        """Gets the id of this ApiTimelineEventDetail.  # noqa: E501


        :return: The id of this ApiTimelineEventDetail.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApiTimelineEventDetail.


        :param id: The id of this ApiTimelineEventDetail.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def _date(self):
        """Gets the _date of this ApiTimelineEventDetail.  # noqa: E501


        :return: The _date of this ApiTimelineEventDetail.  # noqa: E501
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this ApiTimelineEventDetail.


        :param _date: The _date of this ApiTimelineEventDetail.  # noqa: E501
        :type: str
        """

        self.__date = _date

    @property
    def event(self):
        """Gets the event of this ApiTimelineEventDetail.  # noqa: E501


        :return: The event of this ApiTimelineEventDetail.  # noqa: E501
        :rtype: str
        """
        return self._event

    @event.setter
    def event(self, event):
        """Sets the event of this ApiTimelineEventDetail.


        :param event: The event of this ApiTimelineEventDetail.  # noqa: E501
        :type: str
        """

        self._event = event

    @property
    def note(self):
        """Gets the note of this ApiTimelineEventDetail.  # noqa: E501


        :return: The note of this ApiTimelineEventDetail.  # noqa: E501
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this ApiTimelineEventDetail.


        :param note: The note of this ApiTimelineEventDetail.  # noqa: E501
        :type: str
        """

        self._note = note

    @property
    def photo_count(self):
        """Gets the photo_count of this ApiTimelineEventDetail.  # noqa: E501


        :return: The photo_count of this ApiTimelineEventDetail.  # noqa: E501
        :rtype: int
        """
        return self._photo_count

    @photo_count.setter
    def photo_count(self, photo_count):
        """Sets the photo_count of this ApiTimelineEventDetail.


        :param photo_count: The photo_count of this ApiTimelineEventDetail.  # noqa: E501
        :type: int
        """

        self._photo_count = photo_count

    @property
    def is_scattered(self):
        """Gets the is_scattered of this ApiTimelineEventDetail.  # noqa: E501


        :return: The is_scattered of this ApiTimelineEventDetail.  # noqa: E501
        :rtype: bool
        """
        return self._is_scattered

    @is_scattered.setter
    def is_scattered(self, is_scattered):
        """Sets the is_scattered of this ApiTimelineEventDetail.


        :param is_scattered: The is_scattered of this ApiTimelineEventDetail.  # noqa: E501
        :type: bool
        """

        self._is_scattered = is_scattered

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiTimelineEventDetail, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiTimelineEventDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
