# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApiVlmQueueStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'running': 'bool',
        'total': 'int',
        'completed': 'int',
        'failed': 'int',
        'current_file': 'str'
    }

    attribute_map = {
        'running': 'running',
        'total': 'total',
        'completed': 'completed',
        'failed': 'failed',
        'current_file': 'currentFile'
    }

    def __init__(self, running=None, total=None, completed=None, failed=None, current_file=None):  # noqa: E501
        """ApiVlmQueueStatus - a model defined in Swagger"""  # noqa: E501
        self._running = None
        self._total = None
        self._completed = None
        self._failed = None
        self._current_file = None
        self.discriminator = None
        if running is not None:
            self.running = running
        if total is not None:
            self.total = total
        if completed is not None:
            self.completed = completed
        if failed is not None:
            self.failed = failed
        if current_file is not None:
            self.current_file = current_file

    @property
    def running(self):
        """Gets the running of this ApiVlmQueueStatus.  # noqa: E501


        :return: The running of this ApiVlmQueueStatus.  # noqa: E501
        :rtype: bool
        """
        return self._running

    @running.setter
    def running(self, running):
        """Sets the running of this ApiVlmQueueStatus.


        :param running: The running of this ApiVlmQueueStatus.  # noqa: E501
        :type: bool
        """

        self._running = running

    @property
    def total(self):
        """Gets the total of this ApiVlmQueueStatus.  # noqa: E501


        :return: The total of this ApiVlmQueueStatus.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this ApiVlmQueueStatus.


        :param total: The total of this ApiVlmQueueStatus.  # noqa: E501
        :type: int
        """

        self._total = total

    @property
    def completed(self):
        """Gets the completed of this ApiVlmQueueStatus.  # noqa: E501


        :return: The completed of this ApiVlmQueueStatus.  # noqa: E501
        :rtype: int
        """
        return self._completed

    @completed.setter
    def completed(self, completed):
        """Sets the completed of this ApiVlmQueueStatus.


        :param completed: The completed of this ApiVlmQueueStatus.  # noqa: E501
        :type: int
        """

        self._completed = completed

    @property
    def failed(self):
        """Gets the failed of this ApiVlmQueueStatus.  # noqa: E501


        :return: The failed of this ApiVlmQueueStatus.  # noqa: E501
        :rtype: int
        """
        return self._failed

    @failed.setter
    def failed(self, failed):
        """Sets the failed of this ApiVlmQueueStatus.


        :param failed: The failed of this ApiVlmQueueStatus.  # noqa: E501
        :type: int
        """

        self._failed = failed

    @property
    def current_file(self):
        """Gets the current_file of this ApiVlmQueueStatus.  # noqa: E501


        :return: The current_file of this ApiVlmQueueStatus.  # noqa: E501
        :rtype: str
        """
        return self._current_file

    @current_file.setter
    def current_file(self, current_file):
        """Sets the current_file of this ApiVlmQueueStatus.


        :param current_file: The current_file of this ApiVlmQueueStatus.  # noqa: E501
        :type: str
        """

        self._current_file = current_file

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiVlmQueueStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiVlmQueueStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
