# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApiGetAppSettingListResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'app_setting_list': 'list[ApiAppSettingInfo]'
    }

    attribute_map = {
        'app_setting_list': 'appSettingList'
    }

    def __init__(self, app_setting_list=None):  # noqa: E501
        """ApiGetAppSettingListResponse - a model defined in Swagger"""  # noqa: E501
        self._app_setting_list = None
        self.discriminator = None
        if app_setting_list is not None:
            self.app_setting_list = app_setting_list

    @property
    def app_setting_list(self):
        """Gets the app_setting_list of this ApiGetAppSettingListResponse.  # noqa: E501


        :return: The app_setting_list of this ApiGetAppSettingListResponse.  # noqa: E501
        :rtype: list[ApiAppSettingInfo]
        """
        return self._app_setting_list

    @app_setting_list.setter
    def app_setting_list(self, app_setting_list):
        """Sets the app_setting_list of this ApiGetAppSettingListResponse.


        :param app_setting_list: The app_setting_list of this ApiGetAppSettingListResponse.  # noqa: E501
        :type: list[ApiAppSettingInfo]
        """

        self._app_setting_list = app_setting_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiGetAppSettingListResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiGetAppSettingListResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
