# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApiExecuteSQLRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sql': 'str',
        'limit': 'int'
    }

    attribute_map = {
        'sql': 'sql',
        'limit': 'limit'
    }

    def __init__(self, sql=None, limit=None):  # noqa: E501
        """ApiExecuteSQLRequest - a model defined in Swagger"""  # noqa: E501
        self._sql = None
        self._limit = None
        self.discriminator = None
        if sql is not None:
            self.sql = sql
        if limit is not None:
            self.limit = limit

    @property
    def sql(self):
        """Gets the sql of this ApiExecuteSQLRequest.  # noqa: E501


        :return: The sql of this ApiExecuteSQLRequest.  # noqa: E501
        :rtype: str
        """
        return self._sql

    @sql.setter
    def sql(self, sql):
        """Sets the sql of this ApiExecuteSQLRequest.


        :param sql: The sql of this ApiExecuteSQLRequest.  # noqa: E501
        :type: str
        """

        self._sql = sql

    @property
    def limit(self):
        """Gets the limit of this ApiExecuteSQLRequest.  # noqa: E501


        :return: The limit of this ApiExecuteSQLRequest.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this ApiExecuteSQLRequest.


        :param limit: The limit of this ApiExecuteSQLRequest.  # noqa: E501
        :type: int
        """

        self._limit = limit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiExecuteSQLRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiExecuteSQLRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
